RackHD/on-http

data/templates/centos-ks

To fix ODR-260 and provide solution for RHEL/CentOS 7 network setting failure issue in some cases (apply to ODR-319). 
* ODR-260: RHEL/CentOS bootstrap failed to set network on D51 sometimes
* Fix issue that T41 network setting won't take effective until we reboot OS manually after RHEL7/CentOS7 bootstrapping (part of ODR-319).
I tested this change with configuration of (RHEL7/CentOS7+T41), (RHEL7+D51). All network settings are good and it solved RHEL7/CentOS7 network related issues we have seen before.

Fix ODR-260 and provide solution for RHEL/CentOS 7 network setting failure issue

---

lib/api/nodes.js
spec/lib/api/nodes-spec.js

Only enclosure node supports Panduit OBM settings, so adding check of invalid obm settings when user post or patch this info.
In this implementation, compute node only supports ipmi obm settings, and enclosure node only supports Panduit.
https://hwjiraprd01.corp.emc.com/browse/MAG-222
Related PRs:
https://github.com/RackHD/on-tasks/pull/55
https://github.com/RackHD/on-core/pull/22

Added obm setting check when posting or patching in nodes api

---

lib/api/nodes.js
lib/services/nodes-api-service.js
spec/lib/api/nodes-spec.js
spec/lib/services/nodes-api-service-spec.js

Update removing node based on @iceiilin 's PR https://github.com/RackHD/on-tasks/pull/26 
1. when removing a compute node, check the relationship within this node, if it's enclosed by an enclosure node, after remove compute node, also remove the relationship within enclosure node, when all nodes   of an enclosure are removed, remove the enclosure automatically.
2. add nodes-api-service.js to handle nodes api function.
3. add unit tests

remove  node update based on enclosure node update

---

package.json
static/apidoc/header.md

* renaming from Monorail to RackHD API for the generated documentation
* adding a header link to our hosted, latest online documentation for a developer's guide

renaming to RackHD API

---

data/templates/centos-ks

Reverts RackHD/on-http#31
From https://github.com/RackHD/on-http/pull/31
```
well crud. -1 -1 -1 -1 -1 -1 -1
The issue that spawned this wasn't fixed by it in the real deployment. In fact, during deployment testing, the .ifname=0 (going back to trusting the old-style kernel names) showed inconsistent naming during installs: a few times eth0 got mapped to the first mez card, most other times it got mapped to the 2nd mez.
We need to revert this, since it will also mess up regression tests because of the name changes again.
```
@pengz1 @keedya @yyscamper @zyoung51 @stuart-stanley 
Redirect questions to me to @stuart-stanley, it just seems he doesn't have permissions to create the revert PR so I'm doing it for him :)

Revert ac2b3983eede591bc37ad6b97f1de06d9be05781

---

data/templates/esx-ks

Adjusted this value since it wasn't valid and causes the first boot config not to take place unless another reboot is manually applied.
Here is an error if you manually try to run the old command on 5.5
esxcli system shutdown reboot -d 5 -r "Rebooting after first boot host configuration"
Invalid data constraint for parameter 'delay'. Expected integer in the range 10-4294967295

esx-ks reboot delay fix for 5.5 support

---

data/templates/esx-ks

- Defining a 'vmnic#' device name in networkDevices will select which vmnic is
bound to vSwitch0 during initial install.
- 'esxSwitchName' parameter can be specified in networkDevices objects to
control which vSwitch the port group is bound to.  This example would put
the pg-name portgroup on vSwitch1 and put vmk# in the pg-name portgroup with
the proper IP settings:
{
"device": "pg-name",
"esxSwitchName": "vSwitch1",
"ipv4": {
"netmask": "255.255.255.0",
"ipAddr": "172.31.128.10",
"gateway": "172.31.128.1"
}
}
- 'switchDevices' parameter is added to create vswitches and control what uplinks
are on the switch.  if 'uplink' is not specified, then the switch is created with
no uplinks (internal switch)
This would create vSwitch1 with vmnic1 as an uplink, and create "internal name" with no …

VEY-230: Add switch configurationa nd vmnic configuration to esx-ks

---

data/templates/centos-ks
data/templates/esx-ks

Update ks file to include driveId option for bootstrap.
For esx, we add driveId with default value "firstdisk". If no driveId is assigned, --firstdisk value will be used in ks. Other wise --drive value will be enabled.
For centos, driveId defautl is sda if no driveId is assgined. However since 6.5 doesn't have --boot-drive value, we need to judge if centos/rhel version is 6.5
This PR is related to https://github.com/RackHD/on-tasks/pull/69.

Update ks start file to include driveId option for bootstrap

---

data/templates/setup_iso.py

yeah, I know it's ghetto - but I needed to drop the symlinks into another
directory for the `vagrant up` demo setup, so this option defaults to
`/var/renasar` as the old script, but allows you to add
`--link /home/vagrant/src` to support for Vagrant ISO unpack and installation
instructions I'm cobbling

adding an option 'symbolic link' base argument

---

data/templates/get_driveid.js

If there is only SATADOM in the system, the previous get_driveid script will fail due to cannot find the directory "/dev/disk/by-path", this script is to ignore such error, so this can ensure we still get correct catalog data for the only SATADOM disk.
@RackHD/corecommitters @iceiilin @pengz1

fix the case for driveid catalog when only SATADOM in system

---

spec/lib/api/tasks-spec.js

- Update unittests to switch from findOne to find in on-core
- Depends on GRIP-17 PR in on-core

GRIP-17: Add scoping to templates

---

data/templates/centos-ks
data/templates/esx-ks

For ESXi/RHEL/CentOS installation, previously we will clear all disks partition, so the compute node can only install one OS. With this fix, user can install different OS in different disk, the kickstart file will only clear the target drive partition (not all), so different OS can coexist.
@RackHD/corecommitters @iceiilin @sunnyqianzhang @pengz1 @WangWinson

install os only clear partition for target disk, not all

---

lib/api/nodes.js

https://hwjiraprd01.corp.emc.com/browse/ODR-346 complaining the inconsistent return code between operation and doc about deleting active workflow api.
Add success code 204 in apidoc, since "204 No Content: The server successfully processed the request, but is not returning any content" from wikipedia; there is no active workflow after this command, so we can view it as success, though no graph id will be returned.

Modify apidoc about deleting active workflow

---

data/profiles/boot-livecd.ipxe

GRIP-22: Add support for booting LiveCD

---

data/templates/centos-ks

to support additional calls into RackHD for installing KVM packages per details at https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Virtualization/sect-Virtualization-Installing_the_virtualization_packages-Installing_KVM_packages_on_an_existing_Red_Hat_Enterprise_Linux_system.html
requires https://github.com/RackHD/on-tasks/pull/90 to be functional, but should merge cleanly regardless

adding optional KVM trigger to install KVM related packages

---

data/templates/centos-ks

It is found that with old centos-ks kvm setting, RHEL bootstrap will fail with kvm errors. New centos-ks can solve this problem.

Fix RHEL installtion failure do to kvm issue

---

lib/api/files.js
lib/api/pollers.js
lib/api/profiles.js
lib/api/tasks.js
lib/api/templates.js
lib/api/workflows.js
package.json

Fix some descriptions and typos during review the docs http://servername:8080/docs.
1. correct some method names in docs
2. supplement description for post /tasks/:identifier
3. duplicated name 'poller-get-data' which lead to API missing when generating API docs. rename one 'poller-get-data' to 'poller-get-data-current'
4. fix the port number from 80 to 8080 in docs
@RackHD/rackhd_dev

Fix docs typos and descriptions

---

data/templates/get_smart.sh

This PR is part of change to fix https://hwjiraprd01.corp.emc.com/browse/ODR-356
The controller ID from get_smart script may vary for different drive connect to the same controller, so leave the controller ID to be defined in northbound API
@RackHD/corecommitters @cgx027 @sunnyqianzhang

[ODR-356] Rename controller_ID to host_ID in smart catalog

---

app.js
lib/services/common-api-presenter.js
lib/services/http-service.js
lib/services/sku-pack-service.js
skupack.d/README.md
spec/helper.js
spec/lib/api/nodes-spec.js
spec/lib/services/sku-pack-service-spec.js
spec/lib/services/sku-static/.gitignore

- Load sku pack configuration files from 'skuPackRoot'.  The config
files provide sku specific template/static directories that will
override the global directories if the node has a 'sku' value.
- Modify on-http to get the 'sku' specific template if a 'sku' value
is defined for the nodeid attached to the requestor IP.
- Modify on-http to serve the 'sku' specific static root if a 'sku'
value is defined for the nodeid attached to the requestor IP.
- Changed the express chaining to store the IP and nodeID in the first
middleware function.

GRIP-36: SKU Pack Support

---

lib/api/lookups.js
lib/api/nodes.js
package.json

Fork apidoc-swagger until query input types are supported

Clarify query parameter types

---

lib/services/http-service.js
package.json
spec/lib/api/tasks-spec.js
spec/lib/services/http-service-spec.js
spec/lib/services/sku-pack-service-spec.js

Implement http proxy via express-http-proxy module in http-service.js.
Proxy settings should will be input from monorail.json with key name "httpProxies";
"httpProxies" is supposed to be an array and each proxy element could include 3 items:
(1) Server info, which is a must.
(2) Local/remote paths are optional and will be root path by default if not provided.

Add creating proxy function to http-service

---

data/templates/get_driveid.js
package.json
spec/data/templates/get_driveid-spec.js

This PR is to fix ODR-422. It is reported on vBMC that bootstrap will stopped due to DVD-ROM is the first devices in disk list.
In the PR we filter devices via device name sdx or hdx thus DVD_ROM will not be in drive list any more.
Tests were done on D51, T41, Rinjin and D51 vBMC in SH lab and passed.

Fix ODR-422: DVD-ROM will be first disk during bootstrap

---

lib/services/nodes-api-service.js
spec/lib/services/nodes-api-service-spec.js

Implement full function about deleting nodes and update its related ones based on "relations" field in nodes/ document. It is invoked by ODR-314 (https://hwjiraprd01.corp.emc.com/browse/ODR-314) requiring removing compute nodes in an enclosure when user asks to delete that enclosure node.
Currently there is only (enclosedBy, encloses) relation in node, but it is easily extensible to cover other relations such as (powers, powerBy) or (compute node use dae, dae used by compute node). When deleting one node, RackHD should also delete or update its corresponding nodes in different conditions.
There are 3 types of operations to deal with corresponding (I call it "target node" in code and here) nodes:
* delete all target nodes. 
e.g. delete enclosure node -> delete compute node as well
* delete …

add deleting all types of nodes

---

.gitignore
Gruntfile.js
README.md
install-web-ui.sh
lib/services/http-service.js
package.json

Github provides a nice ability to download a zip file for any branch. Since the UI is hosted on `gh-pages` it can be used to install the UI for `on-http`. I created a script that will download and extract the UI and serve it at `/ui`. This script will get automatically run with `npm install`.

Adds web ui install script

---

data/profiles/install-esx.ipxe
data/profiles/install-esx60.ipxe

undionly.kpxe from ipxe is not the original gPXE undionly.kkpxe from syslinux which has been validated for installing ESXi on multiple platforms, correct it here. This will fix the chainload failure issue when installing ESXi OS
related PR:
https://github.com/RackHD/RackHD/pull/70
https://github.com/RackHD/on-imagebuilder/pull/17

Change ipxe's undionly.kpxe to syslinux's undionly.kkpxe

---

index.js
spec/lib/api/index-spec.js
spec/lib/services/http-service-spec.js
spec/lib/services/ws-service-spec.js

Previous calls of helper.requireWrapper() didn't designate required module path, so the default ones are the path of on-core/di.js and its parent directories. Modules can be successfully injected when on-core is a real module under RackHD/on-http/node_modules/on-core, but will throw error about failure to find modules when using "npm link" in on-http to create a symbolic link of on-core to the local source code, since in the latter case, the working directory is RackHD/on-core/lib/di.js, and nodejs cannot find  modules in RackHD/on-http/node_modules.
So __dirname is added as a parameter in helper.requireWrapper() to ask di.js to find modules in current directory in on-http.

Add module path for di injector

---

lib/fittings/on_swagger_router.js
swagger_config/default.yaml

A change to swagger-node-runner (https://github.com/theganyo/swagger-node-runner/
commit/5cc5df13f0b880b1b42350e1f1d914978b066820) has not been packaged upstream
yet.  This commit makes the change locally and should be removed once the updated 
swagger-node-runner package is included into swagger-express-mw.

Add local copy of swagger_router fitting

---

data/templates/bootstrap.js

As discussed in https://github.com/RackHD/on-core/pull/70, add check of accept exit code to ensure it is an array of number. Otherwise this value won't take effect in evaluating stdout. 
It can cover the case when accepted exit code is '127', and actual exit code is 1 resulting accepting this error unexpectedly.
This PR can be merged independently without impacting discovery process.

Ensure the accepted exit code is an array of number in bootstrap.js

---

lib/api/workflows.js
spec/lib/api/workflows-spec.js

ON-2719 - Add additional POST workflow route necessary to support node refresh workflow.
@benbp

ON-2719 - Add additional POST workflow route necessary to

---

.travis.yml
build-package.bash
debianstatic/python-client/changelog.in
debianstatic/python-client/control.in
debianstatic/python-client/postinst
debianstatic/python-client/postinst.in
debianstatic/python-client/python-on-http.dirs
debianstatic/python-client/python-on-http.install
debianstatic/python-client/python-{{name}}.dirs.in
debianstatic/python-client/python-{{name}}.install.in
static/redfish.yaml

- Templatize python-client debian files.
- Generate debian packages for v2.0 and redfish API clients.
- Fixed redfish swagger type definitions.
Note:  The 2.0 and redfish client libraries will be pushed to pypi after more testing.  Currently these packages are uploaded manually.
@RackHD/corecommitters @zyoung51 @brianparry @geoff-reid @keedya @tannoa2 @uppalk1

Create 2.0 and redfish 1.0 API client libraries

---

.dockerignore
Dockerfile

REQUIRES: https://github.com/RackHD/on-core/pull/79
* Switched rackhd/on-core to use an alpine linux base image.
* Now installs RackHD swagger-ui.
* Use CMD instead of ENTRYPOINT for easier debugging.

Update Dockerfile for Alpine Linux

---

lib/fittings/swagger_render.js
lib/services/swagger-api-service.js
spec/lib/services/swagger-api-service-spec.js

* Add error processing helper to swagger API service.
* Add options object to swagger controllers to allow custom success response.
This PR supersedes https://github.com/RackHD/on-core/pull/78.

2.0 API error handling fixes.

---

lib/api/2.0/pollers.js
lib/api/serdes/pollers.js
lib/serializables/v2/pollers.js
lib/services/pollers-api-service.js
lib/services/swagger-api-service.js
spec/lib/services/swagger-api-service-spec.js
static/monorail-2.0.yaml

This change includes the following methods/routes.  @srinia6 will be submitting a follow-on PR with unit tests for these routes.
* GET /pollers/library
* GET /pollers/library/{identifier}
* GET /pollers
* GET /pollers/{identifier}
* POST /pollers
* PATCH /pollers/{identifier}
* DELETE /pollers/{identifier}
* PATCH /pollers/{identifier}/pause
* PATCH /pollers/{identifier}/resume
* GET /pollers/{identifier}/data
* GET /pollers/{identifier}/data/current

Add 2.0 API pollers routes

---

data/profiles/install-trusty.ipxe
data/templates/ubuntu-trusty-preseed

* Replaced /ubuntu_trusty (which seems to be a personal mirror a dev setup) with correct locations that will work when /ubuntu is proxying http://archive.ubuntu.com/ubuntu/
* Removed the squashfs referenced in the preseed. It is not needed, and attempting to inject one creates a fragile dependency.
* Added the port to the host string.

Updating ubuntu ipxe and preseed files

---

lib/api/1.1/northbound/nodes.js
lib/api/2.0/nodes.js
lib/api/2.0/pollers.js
lib/api/redfish-1.0/chassis.js
lib/api/redfish-1.0/service-root.js
lib/api/redfish-1.0/systems.js
lib/fittings/json_error_handler.js
lib/fittings/swagger_render.js
lib/fittings/swagger_serdes.js

clean all the jshint errors for on-http
vagrant@rackhd-demo:~/src/on-http$ ./node_modules/.bin/jshint -c .jshintrc lib index.js || true
lib/api/1.1/northbound/nodes.js: line 33, col 5, 'Errors' is defined but never used.
lib/api/2.0/nodes.js: line 9, col 44, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 13, col 58, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 17, col 45, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 21, col 47, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 25, col 45, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 29, col 48, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 33, col 65, 'res' is defined but never used.
lib/api/2.0/nodes.js: line 37, col 51, 'res' is defined but never used. …

Clean jshint errors

---

lib/services/redfish-validator-service.js
spec/lib/api/redfish-1.0/system-spec.js
spec/lib/services/redfish-validator-service-spec.js

- The object is parsed and all objects within that contain an
'odata.type' are extracted.  Each odata.type is looked up in
the schema dataset and then the object is validated against
the schema.

[redfish] Validate objects using odata.type if it is supplied

---

data/templates/redfish.1.0.0.computersystem.1.0.0.json
lib/api/1.1/northbound/workflows.js
lib/api/redfish-1.0/task-service.js
lib/services/nodes-api-service.js
lib/services/redfish-validator-service.js
lib/services/workflow-api-service.js
spec/lib/api/1.1/workflows-spec.js
spec/lib/api/redfish-1.0/task-service-spec.js
spec/lib/services/nodes-api-service-spec.js
spec/lib/services/workflow-api-service-spec.js

More smoke test fixes:
- Missed one occurrence of replacing the deprecated way to check for an active graph for a node.
- Making some changes to the workflow library routes. These routes *already* do not work (https://github.com/RackHD/RackHD/issues/89), but tests have passed with false positives so far because the `/workflows/library` route gets redirected to the `/workflows/<id>` route. Previously, this route improperly returned a 200 no matter what. Because it was changed to return a 404 on failure to find a workflow, a bunch of the false positive tests are now failing as they should be.
I think this may be controversial in regards to the `/workflows/library/*` addition/change, but I'm kind of at a loss for what to do. I don't want to continue with the current broken behavior just to …

Workflow related API fixes

---

spec/lib/api/2.0/pollers-spec.js
spec/lib/services/pollers-api-service-spec.js

@dalebremner @brianparry @geoff-reid @abildw @RackHD/corecommitters

pollers unit-test for 2.0 and services 

---

.travis.yml
package.json
static/monorail.yml

Generate 1.1 API client library from YAML definitions, remove apidoc-swagger dependency
@RackHD/corecommitters @WangWinson 
This removes the apidoc-swagger dependency and generates 1.1 client code from static/monorail.yml.  This keeps us consistent,  and probably should have been done this way originally;  it will also account for recent workflow api changes.   Once this goes in I can update pypi and submit the relative RackHD integration script changes, which are ready to go.

Update monorail.yml definitions

---

static/monorail.yml

Python client generator is now point to the monorail.yml, so add the security fields to enable auth in client code.
@RackHD/corecommitters @cgx027

Add security definition for generate python client with auth enabled

---

lib/api/1.1/southbound/profiles.js
lib/services/profiles-api-service.js
spec/lib/api/1.1/profiles-spec.js
spec/lib/api/login/login-spec.js
spec/lib/services/auth-service-spec.js
spec/lib/services/http-service-spec.js
spec/lib/services/profiles-api-service-spec.js

- Option to remove DHCP-Proxy dependency (example dhcpd.conf PR https://github.com/RackHD/RackHD/pull/114) and decouple DHCP service/least file tailing.
- Creates lookup entry based on DHCP bootfile option request query parameters
- Fixed unit-tests to use unique http/https ports that are causing random ADDRINUSE errors
@RackHD/corecommitters @geoff-reid @zyoung51 @uppalk1 @tannoa2 @anhou

Add dynamic and static IP/MAC lookups

---

data/profiles/install-coreos.ipxe
data/templates/install-coreos.sh

This is discussed in this link: https://github.com/RackHD/RackHD/issues/90
Since http proxy often fails for large file transmission especially in vagrant environment, so add the external repo support will provide alternative way to do CoreOS installation.
@RackHD/corecommitters @pengz1 @heckj

add external repo support for CoreOS installation

---

lib/services/http-service.js
package.json
spec/lib/services/http-service-spec.js
spec/lib/services/obm-api-service-spec.js

The issue link is: https://github.com/RackHD/RackHD/issues/90, and some discussion is in the google group: https://groups.google.com/forum/#!topic/rackhd/NAKw1ZXixlQ
This fix is to replace the old proxy library `express-http-proxy` with `http-proxy-middleware`, because `express-http-proxy` has bad performance for big file transmission, because it will first cache all content into memory and then passed to requester. But `http-proxy-middleware` works in a stream way,  the content is gradually passed to the requester, this will dramatically require less memory usage.
I have tested in vagrant environment (with 512M memory), use the `http-proxy-middleware` succeed to download a 3GB file via proxy. But the `express-http-proxy` will make the ORA hangs even I tried to increase the memory to 2GB. …

Improve the http proxy performance for big file transimission

---

.gitignore
HWIMO-BUILD

npm prune --production doesn't work correctly in version 1.3.10.  It ends up removing the redfish-node module form on-tasks node_modules which is needed for on-http.
To work around this, we have to remove node_modules and run 'npm install --production' rather than do 'npm prune --production'.  We cannot just do 'npm install --production on line 14 because we need apidoc for line 15.

Work around npm 1.3.10 bug with prune.

---

lib/api/1.1/northbound/nodes.js
lib/api/1.1/northbound/skus.js
lib/api/1.1/northbound/workflows.js
lib/services/common-api-presenter.js
lib/services/sku-pack-service.js
lib/services/tags-api-service.js
spec/lib/api/1.1/skus-spec.js
spec/lib/services/sku-pack-service-spec.js

When inject the tasks/workflows of SKU pack, it will fail due to defineTask and defineWorkflow error. The root cause is that after @benbp 's workflow change, the previous TaskGraphRunner should be replaced with WorkflowApiService. This PR is to fix this problem together some other minor enhancement:
Changes include:
1. Fix SKU pack defineTask/defineTaskGraph error
2. remove unused taskGraphRunner inject (because it has been replaced with workflowApiService)
3. change POST the SKU pack returns a JSON object, this is the standard response format for all other APIs
@RackHD/corecommitters @zyoung51 @pengz1 @sunnyqianzhang

fix SKU Pack defineTask/defineTaskGraph error

---

app.js
lib/api/2.0/users.js
lib/fittings/swagger_authn.js
lib/fittings/swagger_authz.js
lib/services/acl-service.js
lib/services/auth-service.js
lib/services/http-service.js
package.json
spec/helper.js
spec/lib/api/2.0/users-spec.js
spec/lib/api/login/login-spec.js
spec/lib/api/redfish-1.0/session-service-spec.js
spec/lib/services/auth-service-spec.js
static/monorail-2.0.yaml
static/redfish.yaml
swagger_config/default.yaml

- Fittings are created to enable authn (using x-authentication-type) and
authz (using x-privileges) on a per-method basis defined within the
swagger file
- ACL service is created as an interface to node_acl.  The ACL service
contains the mappings of users to roles, and roles to privileges.
- A /users route is added to 2.0 to enable a starting point for a user
management API.  Initially POST and PUT are supported to create and update
users.  A local user exception is added to permit a localhost connection to
add the first user into the database when authentication is enabled and no
users exist yet.
- The authentication service is refactored to remove the hardcoded default
username/password and to remove decryptable passwords.  Bcrypt is used
instead for 1-way password hashing.

[swagger] Add AuthN/AuthZ processing to routes

---

lib/services/swagger-api-service.js
spec/lib/services/swagger-api-service-spec.js

Add parser for swagger query parameter objects.  Only queries explicitly added as parameters in swagger.yaml will be parsed.  No routes support queries yet; this work will be submitted in another PR.
String type queries can be logically ORed by seperating them with a '+'.  For example, ?name='John+George' matches resources with name=John or name=George.

Add swagger query parser

---

data/profiles/defaultboot.ipxe
lib/api/1.1/southbound/profiles.js
lib/serializables/v1/boot.js
lib/serializables/v1/node.js
lib/services/profiles-api-service.js
spec/lib/services/profiles-api-service-spec.js

resolve https://github.com/RackHD/RackHD/issues/104
related PR　https://github.com/RackHD/on-dhcp-proxy/pull/29
@RackHD/rackhd_dev @RackHD/corecommitters @ytjohn 
a brief usage is below, details will be in another PR for RackHD/docs
run PATCH method to node to apply default ipxe boot setting, the fileds 'profile','option' is must required, 'profile'  could be customized, the fields in 'options' should be the same with the parameters in customized profile.  a default profile 'defaultboot.ipxe' is provided for convenience.
```
$ curl -X PATCH -H "Content-Type: application/json" --data @boot.json http://localhost:8080/api/common/nodes/{identifer}
```
a example of boot.json  is below:
```
{
"bootSettings":{
"profile":"defaultboot.ipxe",
"options":{
"url":"http://172.31.128.1:9080/common", …
```

Support default ipxe bootSettings

---

lib/api/1.1/northbound/nodes.js
lib/services/nodes-api-service.js
spec/lib/services/nodes-api-service-spec.js

At the request of @stuart-stanley. A 404 indicates an illegal request, most likely that the node ID doesn't exist at all, as compared to a legitimate request that just returns empty (e.g. are there active workflows? no).

Don't return a 404 when there is no active workflow for a node

---

lib/api/2.0/tasks.js
lib/fittings/swagger_render.js
lib/services/http-service.js
lib/services/swagger-api-service.js
spec/lib/api/2.0/tasks-spec.js
static/monorail-2.0-sb.yaml

Added Southbound /tasks rout to the 2.0 API.
Right now all swagger routes, including the new tasks route, appear on both the southbound and northbound interfaces.  I am working on changes that make the routes available only on the correct interfaces.  This will be a different pull request.

Add /tasks route to 2.0 API

---

data/profiles/install-coreos.ipxe
data/templates/install-coreos.sh

- partial resolution to https://github.com/RackHD/RackHD/issues/146 and
include 'current' in profile explicitly so we can use <%repo%> in the
rendered install template correctly.
- requires a change to the configuration in RackHD proxies to fully operate (https://github.com/RackHD/RackHD/pull/147)
- additionally requires https://github.com/RackHD/on-tasks/pull/147 for a default 'version' for CoreOS install task

use 'repo' as base_url in profile for CoreOS

---

lib/fittings/swagger_locals.js
lib/services/redfish-validator-service.js
spec/lib/api/redfish-1.0/chassis-spec.js
spec/lib/api/redfish-1.0/registry-spec.js
spec/lib/api/redfish-1.0/session-service-spec.js
spec/lib/api/redfish-1.0/system-spec.js
spec/lib/services/redfish-validator-service-spec.js
static/redfish.yaml
swagger_config/default.yaml

- Add parameter handler fittings to perform parameter translation/setup
functions and add a handler that will extract a node id and setup the
res.locals.scope to enable northbound sku views.
- Update redfish template scope to use the pre-established res.locals.scope
- Update redfish rendering to add sku/env as done in common-api-presenter

Add northbound sku support

---

lib/api/2.0/workflowGraphs.js
lib/api/2.0/workflowTasks.js
lib/api/2.0/workflows.js
lib/services/nodes-api-service.js
lib/services/swagger-api-service.js
lib/services/workflow-api-service.js
spec/lib/api/2.0/workflowGraphs-spec.js
spec/lib/api/2.0/workflowTasks-spec.js
spec/lib/api/2.0/workflows-spec.js
spec/lib/services/nodes-api-service-spec.js
spec/lib/services/swagger-api-service-spec.js
spec/lib/services/workflow-api-service-spec.js
static/monorail-2.0.yaml

* GET, POST, DELETE, cancel a workflow.
* GET, PUT, DELETE a graph definition.
* GET, PUT, DELETE a task definition.
* active query param to workflows route
Separate the workflows routes into workflows /workflows/graphs and /workflows/tasks.  The graphs route is used for graph definitions. ant the tasks route is used for task definitions  Some semantics are now inconsistent with /nodes/:identifier/workflows.  This will be cleaned up in another PR.
See https://groups.google.com/forum/#!topic/rackhd/SvggYYKeeaQ for more detailed discussion.
This change has contributions from @dalebremner @abildw and @srinia6 
Depends on https://github.com/RackHD/on-core/pull/107

Add v2.0 workflows API

---

lib/api/2.0/nodes.js

Fix a bug causing 200 to be returned from GET /api/2.0/nodes/:id/workflows/active if no workflow is active.  Return 204 instead.

Return 204 if no workflow is active

---

spec/lib/services/pollers-api-service-spec.js

I had found an odd problem, if putting the `eventually` together with `reject` in an unit-testing assertion, both positive and negative judgement will pass. Please see this issue for detail: https://github.com/RackHD/RackHD/issues/54.
I tend to think `Chai-as-Promise` need to fix this, as people is difficult to realize this problem. I will submit an issue for `Chai-as-Promise`. However, at present, we should avoid to write `eventually` with `reject`.
@RackHD/corecommitters @srinia6 @iceiilin @WangWinson @pengz1 @sunnyqianzhang @zyoung51

fix unit-test: eventually should not be together with reject

---

lib/api/2.0/nodes.js
lib/services/nodes-api-service.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/services/nodes-api-service-spec.js
static/monorail-2.0.yaml

* Add swagger API monorail 2.0 support in nodes.js for masterDelTagById
* Add support for masterDelTagById in nodes-api-service.js
* Update monorail-2.0.yaml for master-delete-tag option under /nodes/tags/{tagName}

Master-Delete-Tag option for all nodes with a specified tagName

---

lib/api/2.0/tasks.js
lib/fittings/swagger_render.js
lib/services/task-api-service.js
spec/lib/api/2.0/tasks-spec.js

Remove the use of the common_api_presenter from the tasks 2.0 route.  This allows us to use the swagger renderer to generate the responses instead.

Remove use of common_api_presenter for tasks 2.0 route

---

app.js
data/views/sample.json
index.js
lib/api/2.0/views.js
lib/api/view/view.js
spec/lib/api/2.0/views-spec.js
static/monorail-2.0.yaml

Views are a collection of ejs templates used for rendering resources into views.  The intent of this change is to logically separate templates used for workflows from templates used for presentation of resources.  Additional PRs to integrate views with the render fitting and to add views for various resources are forthcoming.
Depends on https://github.com/RackHD/on-core/pull/109

API 2.0 /views route

---

lib/api/1.1/southbound/profiles.js
lib/api/1.1/southbound/templates.js
lib/services/common-api-presenter.js
lib/services/profiles-api-service.js
spec/lib/services/profiles-api-service-spec.js

exposed to task templates:
- api.server: set to full API server URI
- api.base: set to API base URI
- api.files: set to File API base URI
- api.nodes: set to Nodes API base URI
- context: set to the graph context
- task.nodeId: set to the nodeId of the current graph

Modify template/profile rendering to add options that are normally

---

lib/services/tags-api-service.js
spec/lib/api/1.1/tags-spec.js
static/monorail-2.0.yaml

Updates to tags-api-service to use "generate-tag" key for options
Update monorail-2.0.yaml for POST/tags response code to be 201

Update tags-api-service and monorail-2.0.yaml 

---

lib/services/swagger-api-service.js
spec/lib/services/swagger-api-service-spec.js
static/monorail-2.0.yaml

Depends on https://github.com/RackHD/on-core/pull/112

Clean up error handling in Swagger renderer

---

lib/api/1.1/northbound/files.js
lib/services/files/file-plugin.js

Fix ODR-605 about "Web UI / POST BIOSImage / API not selecting latest image with same basename uploaded for install". 
Metadata array got from on-http file service is in the time order based on waterline mechanism. Change waterline find method to return the list in sorted manner.

Modify files/:filename/latest to return the latest file

---

lib/api/1.1/northbound/tags.js
lib/api/2.0/tags.js
lib/services/tags-api-service.js
spec/lib/api/1.1/tags-spec.js
spec/lib/api/2.0/tags-spec.js

- Handle special characters in tag name
- Return 404 on GET/DELETE when tag resource does not exist
- Return 409 on POST when tag resource already exists
Resolves https://github.com/RackHD/RackHD/issues/179, resolves https://github.com/RackHD/RackHD/issues/180

Tag bugfixes

---

data/profiles/install-esx.ipxe

resolves https://github.com/RackHD/RackHD/issues/183    it's also related to ODR-629
this PR change chain load sequence from monorail-undionly.kpxe -> undionly.kkpxe -> mboot.c32  to monorail-undionly.kpxe->mboot.c32 to avoid the network or NIC driver problem of undionly.kkpxe(syslinux's gPXE)  also simplify the chain load process. 
So now chain load ESXi installer kernel 'mboot.c32' by iPXE(monorail-undionly.kpxe) not by gPXE(syslinux's undonly.kkpxe) the difference is that gPXE has some default environment variable that would be the implicit parameters for booting mboot.c32 such as BOOTIF, SYSUUID,... (this could be seen from gPXE's source code and bootup logs) , but iPXE don't have, For chain loading ESXi installler's mboot.c32, after validation, only BOOTIF parameter is needed to boot …

Fix RackHD github issue #183 about ESXi chainload

---

lib/services/http-service.js

Partial fix of ODR-620 about failure to update BIOS FW. In flash-quanta-bios-graph.js, after finishing FW update, the task POST the result (similar as stdout, >1M) to RackHD. In previous code, on-http refused this request, while the task is waiting for the response from nodes and never ends.
In current skupack implementation, there is no this problem since the output didn't return to RackHD. It is a fix for OnRack 1.2.0 who doesn't apply skupack and keeps using  flash-quanta-bios-graph.js
Removing the return value in on-tasks/ is also another solution, but enlarging the data size here can provide more flexibility for future usage.

Change body parser to allow post files upto 2MB

---

data/templates/set_bmc_credentials.sh

* check the ipmi channel that's available
* use it to issue the ipmi commands
* Linked to gitHub issue :
Resolves https://github.com/RackHD/on-http/issues/211

Script changes to data/templates/set_bmc_credentials.sh

---

data/profiles/install-ubuntu.ipxe

The BOOTIF param (which is originally there) was deleted accidently. This cause the net install fail on DHCP step for multi NIC. 
Verified this on physical node

Add back bootif param

---

data/templates/redfish.1.0.0.eventdestination.json
data/templates/redfish.1.0.0.eventdestinationcollection.json
data/templates/redfish.1.0.0.eventservice.1.0.0.json
lib/api/redfish-1.0/event-service.js
package.json
spec/lib/api/redfish-1.0/event-service-spec.js
static/redfish.yaml

- Added POST /EventService/Subscription route to subscribe to events
- Added GET /EventService to get the root EventService resource
- Added GET /EventService/Subscription/:id route to get subscription resource collection or specific resource
- Added DELETE /EventService/Subscription/:id to delete an existing subscription resource
- Added POST /EventService/Actions/EventService.SubmitTestEvent
- Added poller alert listener, publish EventService types StatusChange (discrete) and Alert (threshold)
- Added unit-tests
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @geoff-reid @keedya

[redfish] Add Redfish EventService resource

---

data/templates/install-ubuntu/post-install-ubuntu.sh
data/templates/install-ubuntu/ubuntu-preseed

- Fix error when rootSshKey not defined in post install script
- Add grub-installer/bootdev section in preseed to prevent installer interrupt question such as below
> [ Install the GRUB boot loader on a hard disk ]
> You need to make the newly installed system bootable, by installing the GRUB boot loader on a       bootable device. The usual way to do this is to install GRUB on the master boot record of your first hard drive. If you prefer, you can install GRUB elsewhere on the drive, or to another drive, or even to a floppy.
> The device should be specified as a device in /dev. Below are some examples:
> "/dev/sda" will install GRUB to the master boot record of your first hard drive;
> "/dev/sda2" will use the second partition of your first hard drive;
@RackHD/corecommitters @pengz1 …

Fix ubuntu templates issues

---

extra/make-deb.sh

All the other branches seemed to have issues with the BRANCH command when ran under travis-ci (related to shallow clone). This ensures that if TRAVIS_BRANCH is present, it will use that instead of making its own determination.

travis shallow clone tweak

---

lib/services/upnp-service.js

@RackHD/corecommitters @johren @zyoung51 @uppalk1 @tannoa2 @keedya @geoff-reid

Set default endpoint when no endpoints are defined in the config

---

lib/services/sku-pack-service.js
spec/lib/api/1.1/skus-spec.js
spec/lib/api/2.0/skus-spec.js
spec/lib/services/sku-pack-service-spec.js

- Change InternalError errors to BadRequest when the issue arises due to
bad data in the skupack file that is posted.
- Move the config.json properties into the model

Refactor config.json into sku model and cleanup error messages

---

lib/api/1.1/northbound/files.js
lib/api/1.1/southbound/files.js
spec/lib/api/1.1/files-spec.js

To solve issue https://github.com/RackHD/on-http/issues/215
- Add file latest and file md5 latest router to south file router
- Add unit test
@RackHD/corecommitters @cgx027

Add file latest and file md5 latest to south API router

---

lib/api/2.0/tags.js
lib/services/tags-api-service.js
spec/lib/api/2.0/tags-spec.js

The previous decodeURI, which was replaced by decodeURIComponent, was
masking an issue in sway.  This change removes the decodeURIComponent,
which is already being done by express and (attempted by) sway and
changes the 2.0 code to use the sway 1.0.0 fix.

Remove decodeURIComponent and add sway 1.0.0 fix

---

data/templates/centos-ks
data/templates/centos.rackhdcallback

This addresses an issue where we end up doing SSH validation before a reboot during a CentOS install. These changes add a "run-once" service that hits an API route to verify the OS is up and running post installation reboot.
Requires RackHD/on-taskgraph#100 and RackHD/on-tasks#202
@RackHD/corecommitters @heckj @zyoung51 @VulpesArtificem @johren @stuart-stanley

[1.2] Add callback API service to centos-ks installer

---

data/templates/esx-ks
data/templates/esx.rackhdcallback

This addresses an issue where we end up doing SSH validation before we're ready during an ESXi install. These changes add a script that hits an API route to verify the OS is up and running during the %firstboot phase of installation and on post installation reboot.
ESXi is much, much more annoying when it comes to creating custom services, or making persistent changes of any kind, so this isn't quite as clean as the solution for the CentOS installer (#279), but it's the same pattern. The mechanisms used here assume ESXi 5.1 or greater (for older versions, we'd need to write to /etc/rc.local instead of /etc/rc.local.d/local.sh).
Requires RackHD/on-taskgraph#103 and RackHD/on-tasks#210
@RackHD/corecommitters @heckj @zyoung51 @VulpesArtificem @johren @stuart-stanley @richav1 @amymullins

[1.2] Add callback mechanisms to ESXi installations

---

data/templates/esx-ks
lib/api/1.1/southbound/router.js

To resolve an issue where the template cannot be rendered because the information
is not in the lookups table.  This change will post to /lookups as the entries
are created, setting the static ip, mac, nodeid relationship in the database, so
the entry can be found when the template is requested to signal the completion of
the kickstart.

Post to lookups with static ip and newly created MAC

---

.dockerignore
.gitignore
Dockerfile

Removes extra copy of node_modules directory which reduces the size of the docker image.
Also adds `static/swagger-ui` to `.gitignore`.

Dockerfile refactor removes extra node_modules

---

data/templates/get_driveid.js
spec/data/templates/get_driveid-spec.js

This addresses RackHD/RackHD#145 to enhance get_driveid.js to get eUSB SSD catalog, but it could not work well when there are two or more eUSB SSDs or there are other non-SCSI Adapters such as SATA.
@RackHD/corecommitters @yyscamper @anhou @panpan0000

Enhance get_driveid.js to get eUSB SSD catalog

---

lib/api/1.1/northbound/profiles.js
lib/api/1.1/northbound/templates.js
lib/api/2.0/views.js
lib/services/sku-pack-service.js
spec/lib/api/1.1/profiles-spec.js
spec/lib/api/1.1/templates-spec.js
spec/lib/services/sku-pack-service-spec.js

* Change PUT /api/1.1/templates and /profiles put to use new loader semantics.
* Change PUT /api/2.0/views to use new loader semantics.
* Changes to skupack service to use templates/profiles.loadFile rather than put.
This change is dependent on https://github.com/RackHD/on-core/pull/143.  Tests will not pass until both changes are merged.

API and SKU pack changes for new template loader.

---

data/templates/centos-ks
data/templates/esx-ks
data/templates/install-ubuntu/ubuntu-interfaces
data/templates/suse-autoinst.xml

1. old 'vlanId' should not be used anymore, 'vlanIds' is recommanded now. but 'vlanId' is still supported with  deprecated message.
2. this PR is integrated with https://github.com/RackHD/on-tasks/pull/215
@RackHD/corecommitters @yyscamper @anhou   @panpan0000 please review.

change all 'vlanId' to 'vlanIds'

---

data/templates/centos-ks
data/templates/centos.rackhdcallback

This addresses an issue where we end up doing SSH validation *before* a reboot during a CentOS install. These changes add a "run-once" service that hits an API route to verify the OS is up and running post installation reboot.
Requires https://github.com/RackHD/on-taskgraph/pull/99 and RackHD/on-tasks#201
@RackHD/corecommitters @heckj @zyoung51 @VulpesArtificem @johren @stuart-stanley

Add callback API service to centos-ks installer

---

lib/api/2.0/templates.js
lib/services/swagger-api-service.js
spec/lib/api/2.0/templates-spec.js
static/monorail-2.0.yaml

GET /api/2.0/templates/metadata -> Get metadata for all templates
GET /api/2.0/templates/metadata/:name -> Get metadata for all templates with name.
GET /api/2.0/templates/metadata/:name?scope=:scope -> Get a single template with specified name in specified scope
GET/PUT /api/2.0/templates/library/:name -> Get/put raw template with specified name in global scope
GET/PUT /api/2.0/templates/library/:name?scope=:scope -> Get/put raw template with specified name in specified scope.
GET /api/2.0/templates/:name -> Southbound templates route.

2.0 API templates route and tests

---

static/monorail.yml

The swagger spec for the 1.1 API is missing a consumes section
for application/json. Code generated with Swagger tooling then
does not properly marshal JSON data when doing things like POST.

Add consumes application/json to 1.1 swagger spec

---

static/monorail.yml

Add misising schema reference for default case that was left out in f708e0e9084a51e6ca02876f2b6f3ee39273d310
Fix swagger spec for body params:
According to the swagger spec, when defining parameters if `in` is `body`
then the `schema` field is required. Using `type` in the current way is
invalid, and actually crashes go-swagger.

Fix swagger spec 11

---

static/monorail.yml

Two commits in this one.
The main one stems from working with generated swagger code, and finding that most of the GET APIs actually return lists/arrays of objects, but the swagger definition is just `type: object` for a schema.  however, the `GET` for `/nodes` is defined correctly.  Fix this by putting in the correct schema for GET calls that return lists.
Conversely, there were a couple of schemas that said they return lists when they actually return a single object.
The second commit removes extraneous whitespace throughout the YAML file. It was getting hard to work with the YAML files in various editors because of the extra spaces throughout the file. Split that out into a second commit in case you don't accept whitespace fixes.
I have more PRs coming to fix the YAML file here -- …

Monorail API return arrays

---

spec/lib/api/1.1/workflows-spec.js
spec/lib/api/2.0/workflowGraphs-spec.js
spec/lib/api/2.0/workflowTasks-spec.js
spec/lib/api/2.0/workflows-spec.js

@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya 
Resolves unit-test failures for dependent PR: https://github.com/RackHD/on-core/pull/145

Update workflow service unit-tests to mock ARP cache in lookup service

---

static/monorail.yml

There are several missing fields for the `node` definition, and some that have the wrong type.  Fix those by doing the following:
- Add missing fields
- sku comes back as the ID/string, not as an object.
- obmSettings is an array not an object
Here is an example node object I get back from the API, to see that it matches:
```
{
"autoDiscover": false,
"catalogs": [],
"createdAt": "2016-05-18T18:40:30.298Z",
"id": "573cb71ed11f55c1075ec878",
"identifiers": [
"08:00:27:2e:69:a6"
],
"name": "08:00:27:2e:69:a6",
"obmSettings": [
{
"config": {},
"service": "noop-obm-service"
}
],
"relations": [
{
"relationType": "enclosedBy",
"targets": [
"572434ae23947dd00a5d8533"
]
}
],
"sku": "572516a873b83ec515d32719",
"tags": [],
"type": "compute",
"updatedAt": "2016-05-18T18:41:44.183Z",
"workflows": []
} …
```

Update node definition for 1.1 swagger spec

---

static/monorail.yml

The 1.1 swagger spec did not have entries for /tags or for
/nodes/<id>/tags.  Add those and a tag object definition.

Add tags API to 1.1 swagger spec

---

lib/api/1.1/northbound/profiles.js
lib/api/1.1/northbound/templates.js
spec/lib/api/1.1/profiles-spec.js
spec/lib/api/1.1/templates-spec.js

* Add contents field to 1.1 API templates/profiles library routes.
Resolves https://github.com/RackHD/RackHD/issues/235

Fix for Issue #235

---

data/templates/esx-ks
data/templates/esx.rackhdcallback

This addresses an issue where we end up doing SSH validation before we're ready during an ESXi install. These changes add a script that hits an API route to verify the OS is up and running during the `%firstboot` phase of installation and on post installation reboot.
ESXi is much, much more annoying when it comes to creating custom services, or making persistent changes of any kind, so this isn't quite as clean as the solution for the CentOS installer (https://github.com/RackHD/on-http/pull/279), but it's the same pattern. The mechanisms used here assume ESXi 5.1 or greater (for older versions, we'd need to write to `/etc/rc.local` instead of `/etc/rc.local.d/local.sh`).
Requires https://github.com/RackHD/on-taskgraph/pull/102 and https://github.com/RackHD/on-tasks/pull/209 …

Add API callbacks to ESXi installer

---

data/templates/install-ubuntu/ubuntu-preseed

when the ubuntu installation's payload's mirror directory is '/mirrors/ubuntu' not '/ubuntu' like  "repo": "http://172.31.128.1:9080/mirrors/ubuntu"  ubuntu os installation workflow cannot work. refine it to be compatible with ubuntu mirror directory like  '/mirrors/ubuntu' 
@RackHD/corecommitters @WangWinson @pengz1

Refine ubuntu installation mirror directory

---

lib/api/1.1/southbound/profiles.js
lib/services/common-api-presenter.js
lib/services/http-service.js
lib/services/profiles-api-service.js
lib/services/workflow-api-service.js
spec/lib/services/profiles-api-service-spec.js
spec/lib/services/workflow-api-service-spec.js

In order to support running the RackHD on-taskgraph and on-http services on a host that does not have Layer-2 network access to the PXE network we need a host that does have access to the PXE network and can proxy requests to the southbound API endpoint over a management network.
The proxy server, nginx in my POC, adds headers to the requests coming from the PXE client that contain headers that will be used during profile, template, and task rendering.
The headers are
X-Real-IP - the actual IP address of the PXE client
X-RackHD-api-proxy-ip - The IP address of the API proxy server
X-RackHD-api-proxy-port - The port of the API proxy server
The proxy server URL is added to the lookup record for the PXE client so that it can be used during task rendering since the original HTTP request is …

add support for Api proxy

---

lib/services/upnp-service.js
spec/lib/services/upnp-service-spec.js

- Send M-SEARCH requests on southbound network from UPnP/SSDP service and publish advertisements to AMQP `on.ssdp` exchange.
- Include 1.1 and Redfish API URNs on southbound membership.
@RackHD/corecommitters @uppalk1 @tannoa2 @zyoung51 @keedya

Add southbound SSDP observer support

---

data/profiles/install-centos.ipxe
data/profiles/install-coreos.ipxe
data/profiles/install-esx.ipxe
data/profiles/install-suse.ipxe
data/profiles/install-ubuntu.ipxe
data/templates/esx-boot-cfg
lib/services/common-api-presenter.js

This will make it easier to point our OS installer workflows toward custom kickstart/preseed files, and in general make changes in this location.
I'm inclined to not add documentation as I consider these more system specific options, since the kickstart files contain special callback scripts for our workflows. However, It's better that they're not hardcoded in the templates themselves (It is much, much harder to trace what files link to what files with OS installers, and will be easier to just look at a task definition and see all the files that will be downloaded).
Requires https://github.com/RackHD/on-tasks/pull/218
Docs: https://github.com/RackHD/docs/pull/283
@RackHD/corecommitters @heckj 
@zyoung51 I also updated the common-api-presenter rendering to add …

Os install params

---

package.json
spec/lib/api/2.0/views-spec.js

This is a fix to recent travis ci error on on-http repository.
I tested in my forked on-http by enable the travis ci, it passes.
The detail root cause is still unknown for me, at least there is error is that the `request` doesn't been returned.
@brianparry @RackHD/corecommitters @pengz1 @iceiilin @WangWinson

fix travisci error by refactor a Http.Api.Views test case

---

data/templates/secure_erase.py

This script is to implement disk erasing functionality.
hdparm, scrub, sg_format tools are integrated. sg_sanitize is also integrated but less likely to be run as many drives doesn't support.
Erasing will run in async-mode so multiple disk erasing time consumed should be the same as the slowest disk.
For each disk, a log file will be created under home directory named disk name. This can help us to understand what happened during erasing and is intended for getting erasing status.
An example to run this script:
sudo python secure_erase.py -t scrub -o nnsa -d "/dev/sdx,/dev/sdy,/dev/sdw"
-t: specify tools to be used
-o: specify erase option under a specified tool
-d: a string contains all disks to be erased.

Orfs153 implement script to run se command for secure erase

---

data/templates/flash_quanta_bmc.sh

Flashing BMC FW would lose network configurations.
This script refers to the implementation in skupack and made some adjustments. 
https://github.com/RackHD/on-skupack/blob/master/quanta-t41/templates/flash_bmc.sh
In the script:
save BMC lan settings,
backup BMC image into RackHD,
flash BMC FW,
restore BMC lan settings.
related PR:
https://github.com/RackHD/on-tasks/pull/221
https://github.com/RackHD/on-taskgraph/pull/110
@johren @zyoung51

[1.2] add script to flash quanta bmc

---

lib/services/workflow-api-service.js
spec/lib/services/upnp-service-spec.js

- Some targets may not have a lookup entry (e.g. Redfish enclosure node only has OBM settings).
- Remove all listeners in upnp service spec.
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya @shanemsully

Allow proxy lookup to fail in workflow service 

---

data/templates/flash_quanta_bmc.sh

Fix ODR 771 in flashing quanta BMC scripts, about error to set BMC IP after flashing Quanta BMC, if ip source is DHCP. 
It happened in MN lab, where BMC IP source is DHCP. Though the "sudo ipmitool lan set 1 ipaddr xxx" after flashing returns the same message as in static IP source, the exit code is 1 rather than 0. Modify the script to skip these network setting steps if the source is DHCP.
Add retry count after mc reset so that total wait time (maximum) is 90s, the same as suggested by vendor after flashing BMC. The original value is 60s, which is not sufficient for stack 13 node 1 at a certain ratio.
@uppalk1 @zyoung51

[1.2] Set bmc ip only when ip source is static when flashing quanta bmc

---

build-package.bash

Only search for `.in` template files in debianstatic when rendering variables.
@RackHD/corecommitters @ytjohn @zyoung51 @uppalk1 @tannoa2 @keedya

Fix debian package builder script

---

lib/api/redfish-1.0/systems.js
spec/lib/api/redfish-1.0/system-spec.js

Fix the issue: 
failed to get processor information with redfish api:/Systems/{identifier}/Processors/{socket} 
https://github.com/RackHD/RackHD/issues/269
The redfish api "/Systems/{identifier}/Processors" always list all the processors including unpopulated processors.
However, when try to get the information of unpopulated processors, the api "/Systems/{identifier}/Processors/{socket} " just response error.
Unpopulated processors should be filtered.

judge the status of processor at list system processors (redfish api)

---

lib/api/2.0/workflows.js
lib/services/nodes-api-service.js
lib/services/workflow-api-service.js
spec/lib/api/2.0/workflows-spec.js
spec/lib/services/nodes-api-service-spec.js
spec/lib/services/workflow-api-service-spec.js
static/monorail-2.0.yaml

We should not be using the mongo ID for anything, but rather passing around the uuid.v4() instanceId attribute. The API docs reference instanceId, but the code does not, so updating for accuracy.
@RackHD/corecommitters 
Requires an integration test change: https://github.com/RackHD/RackHD/pull/268 which is why Jenkins is failing.

Update 2.0 api workflow operations to operate on instanceId attribute

---

data/templates/esx-ks
lib/api/1.1/southbound/router.js

- Attempt to POST the static IP entry to the /lookups when the static IP
is created by the ESX firstboot script.  If the POST operation fails,
then fallback and attempt a PATCH operation.

Add static IP entry to lookups from ESX kickstart

---

lib/services/workflow-api-service.js
spec/lib/services/workflow-api-service-spec.js

Search environment key with 'config.' for graph definition.
This is a similar change as done in https://github.com/RackHD/on-tasks/blob/master/lib/utils/job-utils/workflow-tool.js#L66

Search environment key with 'config.' for graph definition.

---

static/monorail-2.0.yaml
static/redfish.yaml

- The swagger-ui code throws an exception while parsing the schema
object if it is not a reference.  Change to reference to make
swagger-ui happy.
- Added the missing api/2.0 tag to the node ssh GET

Change swagger yaml file for processing by swagger-ui

---

data/templates/centos.rackhdcallback

For ODR-737 https://hwjiraprd01.corp.emc.com/browse/ODR-737. Increase wget completion uri waiting time from 30s to 5 minutes. to cover worse cases that waiting more time for network ready. 5 minutes is just a long enough experience time tested.  C6320 and platfom-H platforms are tested.

Increase completion uri retry time to wait network ready

---

data/templates/esx-ks

**Fix ODR-748** Adding DNS search domain not working in esx-ks template
**solution:**
In the section that processes 'dnsServers,' this
esxcli network ip dns search add <%=domain%>
needs to be changed to this
esxcli network ip dns search add --domain=<%=domain%>
**Fix ODR-751** Setting 'domain' option is effectively required in esx-ks
**solution:**
According to RackHD docs, the default value of 'domain' is 'rackhd', and now it's changed to null. rackhd/on-tasks#250
@RackHD/corecommitters @panpan0000

Fix adding DNS search domain not working in esx-ks template and set domain optional

---

data/profiles/linux-generic.ipxe

Added Linux diag boot profile for EMC diagnostic images.
@RackHD/corecommitters @uppalk1 @tannoa2 @zyoung51 @keedya

Create linux diag profile

---

lib/fittings/swagger_render.js
spec/lib/api/2.0/catalogs-spec.js
spec/lib/api/2.0/config-spec.js
spec/lib/api/2.0/lookups-spec.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/api/2.0/obms-spec.js
spec/lib/api/2.0/profiles-spec.js
spec/lib/api/2.0/schemas-spec.js
spec/lib/api/2.0/skus-spec.js
spec/lib/api/2.0/tags-spec.js
spec/lib/api/2.0/tasks-spec.js
spec/lib/api/2.0/users-spec.js
spec/lib/api/2.0/views-spec.js
spec/lib/api/2.0/workflowGraphs-spec.js
spec/lib/api/2.0/workflowTasks-spec.js
spec/lib/api/2.0/workflows-spec.js

resolves https://github.com/RackHD/RackHD/issues/259
The actual fix for the bug was the line I added to the swagger_render.  @zyoung51 helped me find that fix.
@RackHD/corecommitters @dalebremner @srinia6 @brianparry

fixing issue #259 and unit test cleanup

---

HWIMO-BUILD

The redfish-node package dependency was removed from RackHD.
So the workaround should be cleared to avoid **double npm install** which takes **almost double** time to build deb package.
@RackHD/corecommitters @panpan0000 @jlongever @davidzuhn

Fix double npm install in HWIMO-BUILD

---

data/templates/get_driveid.js
spec/data/templates/get_driveid-spec.js

when install ESXi,  lodash ‘_’  may be before or after disk SN,  like 'XXXXXX_____________' or '_____________YYYYYY' so the esxiWwid may be 
"esxiWwid":"t10.ATA_____QEMU_HARDDISK_XXXXXX_____________" or
"esxiWwid":"t10.ATA_____QEMU_HARDDISK______________YYYYYY"  it's decided by the raw data read by 'hdparm', previously, lodash ’_‘ is fixed before 'SN' in codes. 
this issue is found when installing ESXi6.0 in InfraSIM. with this fix, ESX6.0 could be installed with InfraSIM.
depends on: https://github.com/RackHD/on-imagebuilder/pull/45

Fix sata disk identifier SN

---

lib/services/workflow-api-service.js
spec/lib/services/workflow-api-service-spec.js

resolves https://github.com/RackHD/RackHD/issues/240
Throw error if the graph name is missing or in wrong format.
@RackHD/corecommitters @iceiilin @WangWinson @cgx027 @pengz1

fix issue#240: POST invalid workflow API will always triggers Graph.BootLiveCD

---

lib/api/1.1/northbound/nodes.js

* Allow posting OBM object or array of OBM objects
* Populate response body with obmSettings property
This problem was discovered by @uppalk1 
@RackHD/corecommitters @srinia6 @dalebremner @keedya @BillyAbildgaard

Fix POST /api/1.1/nodes/{identifier}/obm

---

data/templates/centos-ks
data/templates/esx-ks
data/templates/install-ubuntu/post-install-ubuntu.sh
data/templates/install-ubuntu/ubuntu-interfaces
data/templates/install-ubuntu/ubuntu-preseed
data/templates/suse-autoinst.xml
lib/services/common-api-presenter.js

When task-schema is enabled, if an parameter is optional it will not existing in the rendering context, (previously the optional value will be set to null or []). But current template rendering will throw error if the parameter is missing, currently ,we use following syntax to check a parameter is not missing:
```
if (param !== undefined) {
...
}
```
This will cause the ejs error with failing to find the `param`.
The correct syntax should be:
```
if (typeof param !== 'undefined') {
...
}
```
Meanwhile, I have updated all install-os template to let the `domain`/`hostname` to be optional. This is a requirement from this PR (https://github.com/RackHD/on-http/pull/342), that PR only change on ESXi, my PR changes all install-os's template.
Depends on: …

install-os: fix template defect when a value is not existing; change hostname/domain to be optional

---

lib/services/upnp-service.js

This is per upnp/ssdp specification,  node-ssdp library doesn't construct the UDN as expected.
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya @king-jam

Add UUID prefix to SSDP UDN

---

data/templates/esx-ks

**Fix ODR-750** NTP configuration in esx-ks
The solution is adding ntpSevers options to support NTP configuration, so that the users could use the private NTP servers if needed.
@RackHD/corecommitters @panpan0000 
rackhd/on-tasks#259

add NTP configuration in esx-ks

---

lib/services/http-service.js
package.json

- Able to switch on / by default in one place

Consistency for ways to use 2.0 API (common / current)

---

Dockerfile
HWIMO-BUILD
HWIMO-DOC
README.md
extra/make-docs.sh
install-task-doc.sh
lib/services/http-service.js
package.json
static/taskdoc/api_project.js

This change is based on @cgx027 's updates.
- add static router `/taskdoc` to access the task doc
- create task doc build script `install-task-doc.sh`, leveraging tool script [task-annotation-generator](https://github.com/RackHD/on-tasks/blob/master/task-annotation-generator.js)
- add `npm run taskdoc` to existing build script
@RackHD/corecommitters @iceiilin @pengz1

Create build script for task annotation generation

---

lib/services/workflow-api-service.js
spec/lib/services/workflow-api-service-spec.js

This PR is to fix [ODR#787](https://hwjiraprd01.corp.emc.com/browse/ODR-787).
Previously the `defineTaskGraph` leverage creating graph instance to validate whether the graph definition is valid, but some required option may not be ready at  that time (for example when insert a SKU pack which contains some SKU specific graph). The change is to use the new API to validate the graph definition only, it will skip the task rendering and schema validation.
@RackHD/corecommitters @zyoung51 @iceiilin @pengz1 
Depends on: https://github.com/RackHD/on-tasks/pull/273

Fix ODR787: defineTaskGraph only validate definition rather than creating whole graph instance

---

data/profiles/install-ubuntu.ipxe
data/templates/install-ubuntu/post-install-ubuntu.sh
data/templates/install-ubuntu/ubuntu-preseed

- This PR gives the user the choice to install Ubuntu using mounted ISO image or public mirror
- Documentation for this changes will be traced in a different PR
depends on : https://github.com/RackHD/on-tasks/pull/280
@RackHD/corecommitters @jlongever @tannoa2 @uppalk1 @zyoung51

Fix Ubuntu installation's workflow

---

README.md
static/taskdoc/api_project.js

- Add /taskdoc url to readme
- Unify naming 'RackHD Task Annotation'
@RackHD/corecommitters @cgx027 @iceiilin @pengz1

Update readme with taskdoc url and unify the task annotation naming

---

lib/api/2.0/obms.js
lib/services/nodes-api-service.js
lib/services/obm-api-service.js
spec/lib/api/2.0/obms-spec.js
spec/lib/services/nodes-api-service-spec.js
spec/lib/services/obm-api-service-spec.js

require https://github.com/RackHD/on-core/pull/178 asynchronous publish event when operating obm by API, the PUT and other obm update is handled in upsertByNode in on-core https://github.com/RackHD/on-core/pull/178    docs: https://github.com/RackHD/docs/pull/296
@RackHD/corecommitters @zyoung51 @WangWinson

Support obm related node event

---

data/templates/esx-ks

1. Fix ODR-749 Use MAC addresses to create vSwitch uplinks in esx-ks
2. Use MAC addresses to specify the device under networkDevices
@RackHD/corecommitters @panpan0000

Use MAC addresses to create vSwitch uplinks and networkDevices in esx-ks

---

data/views/node.2.0.json
spec/lib/api/2.0/nodes-spec.js
static/schemas/obms/redfish-obm-service.json

- Create Redfish OBM service schema file.
- Fix nodes view template to handle a target list type.
@RackHD/corecommitters @zyoung51 @tannoa2 @uppalk1 @keedya @BillyAbildgaard @srinia6 @dalebremner @geoff-reid
@brianparry @srinia6: One of the changes below changes the relation target value.  Not all relationship values could be a reference to another resource,  for example Redfish endpoint relations:
```
"targets": [
"ComputeElement0",
"StorageElement1"
],
"relationType": "elementEndpoints"
}
``` 
Was the intention to make all properties a reference link?

Add redfish-obm-service schema and fix node view

---

README.md

added link to readthedocs and explanation showing you can substitute api/1.1 for api/2.0 unless otherwise specified.
@RackHD/corecommitters @keedya @srinia6

updating on-http README w/ link to readthedocs

---

lib/api/2.0/files.js
lib/api/2.0/lookups.js
lib/api/2.0/nodes.js
lib/api/2.0/obms.js
lib/api/2.0/profiles.js
lib/api/2.0/skus.js
lib/api/2.0/templates.js
lib/api/2.0/users.js
lib/api/2.0/views.js
lib/api/2.0/workflowGraphs.js
lib/api/2.0/workflowTasks.js
lib/api/2.0/workflows.js
spec/lib/api/2.0/files-spec.js
spec/lib/api/2.0/lookups-spec.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/api/2.0/obms-spec.js
spec/lib/api/2.0/skus-spec.js
spec/lib/api/2.0/templates-spec.js
spec/lib/api/2.0/users-spec.js
spec/lib/api/2.0/views-spec.js
spec/lib/api/2.0/workflowGraphs-spec.js
spec/lib/api/2.0/workflowTasks-spec.js
spec/lib/api/2.0/workflows-spec.js
static/monorail-2.0.yaml

Update YAML to reflect correct return codes. Also, make the return code consistent across the API's as follows:
GETs/PATCH - 200
PUT/POST - 201
DELETE - 204 [No content]
With an exception of PUT - /workflows/{identifier}/action, /nodes/{identifier}/workflows/action and POST /tags/{tagName}/nodes/workflows that returns a 202.
ALL unit-tests pass locally as this PR has unit-test updates as well.
@benbp @keedya @BillyAbildgaard @brianparry @dalebremner @RackHD/corecommitters @zyoung51 @jlongever

YAML return code corrections

---

data/templates/post-windows-install.ps1
data/templates/unattend_server2012.xml

The post-windows-install.ps1 script runs after Windows OS is installed.
The script would first curl unattend_server2012.xml and then look for the vlan values that are in the xml file in a form of comments. 
Below is and example of the vlan value 104 assigned to to port "Ethernet 1"

add vlan support for windows install

---

lib/services/profiles-api-service.js

- Checks `kargs` option type is object before parsing to valid kernel boot string.  If non-object (i.e. string) will just be passed as-is.
@RackHD/corecommitters @uppalk1 @tannoa2 @zyoung51 @keedya

Check kargs object type before parsing

---

data/templates/install-photon/photon-os-ks
lib/api/1.1/southbound/notification.js
lib/api/1.1/southbound/router.js
lib/api/1.1/southbound/templates.js
lib/api/2.0/notification.js
lib/services/common-api-presenter.js
lib/services/notification-api-service.js
spec/lib/api/1.1/notification-spec.js
spec/lib/api/2.0/notification-spec.js
spec/lib/services/notification-api-service-spec.js
static/monorail-2.0-sb.yaml

/notification API defined to replace ```completionUri``` used by os installation, with benifit of not depending to lookup entry, refer to ODR682.
In this PR:
* POST /notification southbound API is defined, used by node to signaling os install finish. 
* Both API 1.1 and API 2.0 compatible.
* Photon OS kickstart file modified to make use of the new notification mechanism.
This PR depends on following PRs:
* https://github.com/RackHD/on-core/pull/184 
* https://github.com/RackHD/on-tasks/pull/284

Add southbound API to pass notification to RackHD (refer to ODR682)

---

lib/api/2.0/schemas2.js
spec/lib/api/2.0/schemas-spec.js
static/monorail-2.0.yaml

List all task schema names
- GET `/schemas/tasks`
Get a schema data with $ref resolved or not
- GET `/schemas/tasks/:id[?resolveRef=true|false]`
Dependency PR : 
https://github.com/RackHD/on-tasks/pull/290
https://github.com/RackHD/on-core/pull/186
@RackHD/corecommitters @iceiilin @cgx027 @pengz1

Create API to GET task schema

---

lib/api/2.0/pollers.js
lib/services/pollers-api-service.js
spec/lib/services/pollers-api-service-spec.js

* Check if poller exists and return 404 if it does not.
* Collapse getPollersByIdDataCurrent into getPollersByIdData.
@RackHD/corecommitters @srinia6 @dalebremner @BillyAbildgaard @keedya @jlongever

Changes to 2.0 pollers/data route

---

lib/services/http-service.js

- enabling trusted proxy in express
- make this option configurable by adding trustedProxy
booleen  in the config file
- by enabling trust proxy in express, if header/x-forwardedFor 
data is available, then req.ip will be populated with the most left IP in xfowardedFor list
- Resolves: https://github.com/RackHD/RackHD/issues/278

Add support to xForwardedFor

---

data/templates/install-coreos.sh

Right now, the CoreOS install task says its finished once the
cloud-config file is downloaded, but this really before the install
even kicks off. Add a line to the install script to hit the
completionUri right before the reboot so we can trigger off that
instead.

coreos install: indicate complete after write to disk

---

data/profiles/rancherOS.ipxe
data/templates/cloud-config.yaml

depends on : https://github.com/RackHD/on-taskgraph/pull/149
depends on: https://github.com/RackHD/on-imagebuilder/pull/52/files
depends on : https://github.com/RackHD/on-tasks/pull/293
references:  
- https://osclouds.wordpress.com/2015/11/23/announcing-a-new-docker-based-hanlon-microkernel
- https://groups.google.com/forum/#!topic/rackhd/cSYYxhtPWY0

Add  profile and templates for the dockerized discovery task

---

static/monorail.yml

Should be 201, not 200
reference: https://github.com/RackHD/on-http/blob/master/lib/api/1.1/northbound/nodes.js#L498
`gorackhd` code generated based on this swagger spec thinks this call fails because its expecting  `200`.

Fix http return code for POST node workflow

---

static/monorail-2.0.yaml

As @heckj suggested, update the swagger yml description for task schema API to avoid any misunderstanding of the usage of the API.
@RackHD/corecommitters @cgx027

Update the description of task schema API to be more accurate

---

data/views/error.2.0.json
lib/fittings/error_handler.js

@RackHD/corecommitters @keedya @BillyAbildgaard @srinia6

Toggle error view stack trace based on minLogLevel

---

data/profiles/boilerplate.ipxe
data/profiles/error.zt
data/profiles/ipxe-info.ipxe
data/profiles/redirect.ipxe
lib/api/1.1/southbound/profiles.js
lib/services/common-api-presenter.js
lib/services/profiles-api-service.js
lib/services/swagger-api-service.js
spec/lib/api/1.1/profiles-spec.js
spec/lib/api/2.0/profiles-spec.js
spec/lib/services/profiles-api-service-spec.js
static/monorail-2.0.yaml

PR for proposal https://groups.google.com/forum/#!topic/rackhd/I81Tl2qkQMI
related on-dhcp-proxy PR  https://github.com/RackHD/on-dhcp-proxy/pull/52
changes:
1. support geting profiles with macs and ips instead of 'macs' and 'mac & ip' for static ip address for both 1.1 and 2.0 GET /profiles route
2. remove duplicated profile rendering for new node 'node.newRecord'
3. refine naming of 'renderProfileFromTaskOrNode' to 'getProfileFromTaskOrNode'
4. treat 'no active workflow and boot settings' as  expected information.
5. remove error.zt to be consistent with @benbp PR https://github.com/RackHD/on-http/pull/376  and also be consistent with 2.0 GET /profiles API
6. fix 2.0 profile service's 'self.res.xxxx' to 'res.xxxx'
@RackHD/corecommitters  @benno  @jlongever

Get profiles with macs and ips

---

data/templates/esx-ks
data/templates/install-photon/photon-os-ks
data/templates/install-photon/photon-os.rackhdcallback
lib/api/1.1/southbound/notification.js
lib/api/2.0/notification.js
lib/services/common-api-presenter.js
lib/services/notification-api-service.js
lib/services/swagger-api-service.js
spec/lib/api/1.1/notification-spec.js
spec/lib/api/2.0/notification-spec.js
spec/lib/services/notification-api-service-spec.js
static/monorail-2.0-sb.yaml

Notification API design refactor:
* Route set to /notification
* In most cases, a notification will send to a node, so the API will accept a nodeId parameter, either in query string or request body, both POST /notification?nodeId=<nodeId> and POST /notification –d ‘{“nodeId”: ”<nodeId>”}’ will work.
* The notification will be routed by AMQP with key “notification.<nodeId>”
* If the notification is send to other identities, say a workflow, the request will look like POST /notification?workflowId=<workflowId> or POST /notification –d ‘{“workflowId”: ”< workflowId >”}’. 
* The notification will be routed by AMQP with key “notification.<workflowId >”
* I will not code for this and leave it till the need comes.
* If no Id are specified in the parameter, the notification will be route by AMQP …

notification API design refactor

---

lib/api/2.0/nodes.js
lib/api/2.0/tags.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/api/2.0/tags-spec.js

Resolves https://github.com/RackHD/on-http/issues/429
Root cause:
The argument order for setNodeWorkflow is not correct.
@RackHD/corecommitters @lhw4d4 @srinia6

Fix issue that fails to POST workflow via tag

---

static/monorail-2.0.yaml

Fix for RackHD Issue [RackHD/RackHD#381](https://github.com/RackHD/RackHD/issues/381  
)
@brianparry @BillyAbildgaard @keedya @dalebremner @srinia6 @RackHD/corecommitters

Issue #381 - add HEAD meathod to the 2.0 templates route.

---

spec/lib/api/2.0/lookups-spec.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/api/2.0/pollers-spec.js
spec/lib/api/2.0/skus-spec.js
static/monorail-2.0.yaml
static/schemas/2.0/lookups.2.0.json
static/schemas/2.0/node.2.0.json
static/schemas/2.0/poller.2.0.json
static/schemas/2.0/skus.2.0.json

* Clear additionalProperties for all schemas.
* Add tags property to nodes schema
* Change unit tests to abide by new schema rules.

Cleanup of 2.0 API schemas

---

lib/api/2.0/nodes.js
lib/services/nodes-api-service.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/services/nodes-api-service-spec.js
static/monorail-2.0.yaml
static/schemas/2.0/node.2.0.json
static/schemas/2.0/relations.2.0.json

adds a rack node type and capabilities to add and remove 'contains'/'containedBy' relationships as per
https://github.com/RackHD/RackHD/wiki/proposal-passively-add-remove-a-rack-node
and
https://github.com/RackHD/RackHD/wiki/proposal-neighborhood-physical-topology
depends on https://github.com/RackHD/on-core/pull/196
@RackHD/corecommitters @pscharla

added rack node type and node relation management

---

lib/services/nodes-api-service.js
lib/services/profiles-api-service.js
spec/lib/services/nodes-api-service-spec.js

for https://github.com/RackHD/RackHD/wiki/proposal-rack-events-notification
@RackHD/corecommitters @pscharla

add a rack added event when a rack node is posted

---

static/monorail-2.0.yaml

fixes a validation error where the rack type is not included in one of the swagger validation schemas for partial node.
@RackHD/corecommitters  @pscharla

fixed validation error bug

---

data/views/workflows.2.0.json
spec/lib/api/2.0/workflows-spec.js
static/monorail-2.0.yaml

Add workflows view and unit-test.
@brianparry @keedya @dalebremner @BillyAbildgaard @RackHD/corecommitters

Add workflows view and unit-test

---

data/templates/bootstrap.js

currently the max buffer size of child process in bootstrap.js is 1000*1024, but the stdout of flashing bios task is 1131830. from the child process document, "largest amount of data (in bytes) allowed on stdout or stderr - if exceeded child process is killed". The original setting prevents the flashing bios from finishing and would result in the successive catalogs task hanging.
Increase the max buffer size to 5MB

Increase the buffer size of child process in bootstrap.js

---

data/templates/bootstrap.js

In bootstrap.js, the data that will be send to RackHD is in the following format
```
{ 
tasks: [ 
{
cmd: 'echo testtest',
stdout: undefined,
stderr: undefined,
error: [Error: stdout maxBuffer exceeded.] 
} ]
}
```
the error object needs to be converted into string so that RackHD can parse it correctly, otherwise as the error field is empty, RackHD would view the task as success, leading successive task (if any) to run unexpectedly. 
Currently bootstrap.js modifies it by referring data.error, which does not exist at all. So changing the logic to modify data.task[index].error

modify the convertion of error info in bootstrap template

---

lib/api/redfish-1.0/systems.js

Fix [ODR869](https://hwjiraprd01.corp.emc.com/browse/ODR-869) and take this chance to fix an outstanding rename work that stated in this issue: https://github.com/RackHD/RackHD/issues/218
@RackHD/corecommitters @gpaulos @cgx027 @pengz1 @iceiilin @WangWinson 
Jenkins: depends on https://github.com/RackHD/on-tasks/pull/333

Fix ODR869: Rename graph options 'osName' for Esx to ESXi in Redfish BootImage API

---

data/templates/esx-ks

To fix @wangzhizheng 's problem about `postInstallCommands` doesn't take effect.
Previous the input:
```
'postInstallCommands': ["esxcli system settings keyboard layout set -l 'Japanese'"]
```
will be rendered into:
```
esxcli system settings keyboard layout set -l &#39;Japanese&#39
```
Change the `<%=` to `<%-` will remain the unescaped raw output, so that the render result is exactly match with input.
@RackHD/corecommitters @zyoung51 @lanchongyizu @cgx027 @wangzhizheng

change esx-ks postInstallCommands to be unescaped

---

lib/api/2.0/nodes.js
lib/api/2.0/obms.js
lib/api/2.0/pollers.js
lib/services/nodes-api-service.js
lib/services/swagger-api-service.js
spec/lib/services/swagger-api-service-spec.js
static/monorail-2.0.yaml

* Add support for /nodes/:id/catalogs query
* Fix obms query
* Add support for querying pollers by type
* Remove unnecessary logical OR support from query parser.

Cleanup 2.0 API queries

---

lib/services/swagger-api-service.js
spec/lib/services/swagger-api-service-spec.js
static/monorail-2.0.yaml

Add sort by name/id in ASC(+) or DSC(-) order for following routes:
pollers
catalogs
workflows
tags
users
templates
nodes
NOTE: The property to sort can be changed in the YAML. Any property not defined in the  "pattern" will throw an validation error.
@RackHD/corecommitters @brianparry @BillyAbildgaard @dalebremner @geoff-reid

Add sorting by name/id and unit-test

---

lib/api/redfish-1.0/chassis.js

Always use the chassis type defined in the sku configuration over the
chassis type defined in the dmi.

[redfish] Resolve ODR-938

---

lib/api/redfish-1.0/event-service.js
lib/api/redfish-1.0/systems.js
lib/services/redfish-validator-service.js
spec/lib/api/redfish-1.0/system-spec.js
static/DSP8010_1.0.0/json-schema-oem/RackHD.BootImage.json
static/redfish.yaml

The issue link: https://hwjiraprd01.corp.emc.com/browse/ODR-905
Simplify change the "additionalProperties" to `true` will not totally fix this problem. All problems that I found are listed below:
- Not allowed additional properties, so that some OS specific parameters cannot pass the validation, such as the `switchDevices` and `ntpServers` for ESXi.
- `vlanId` should be `vlanIds`, and its item should be `number`.
- The JSON schema validator cannot find the BootImage schema file, as it doesn't be added into `tv4`. Use `redfish.validateSchema` will fix this problem.
@RackHD/corecommitters @zyoung51 @jlongever @keedya

ODR905: Fix the redfish API BootImage validation error

---

static/schemas/2.0/user.2.0.json

This is for ODR-833 https://hwjiraprd01.corp.emc.com/browse/ODR-833
This restricts the creation of users to two roles, Administrator and ReadOnly. Previously, anything could be in the roles field. Presently, these are the only two roles acceptable for 2.0.

Added admin and readonly to user.roles schema

---

data/profiles/linux.ipxe

Node discovery fails when using static file server, because basefs and overlayfs are always pulled from API_CB(api.server) rather than file.server.
The solution is to change BASEFS and OVERLAYFS to be full URL instead of file path.
* use overlayfsUri and overlayfsFile to replace overlayfs in task options
* use basefsUri and basefsFile to replace basefs in task options
@RackHD/corecommitters @iceiilin @cgx027 @panpan0000

fix discovery issue when using static file server

---

data/profiles/install-esx.ipxe
data/templates/esx-boot-cfg
data/templates/esx-pxelinux-cfg

To address Young, Zachary's comment in PR (https://github.com/RackHD/on-http/pull/38), we can set the prefix as repo address in esx-boot-cfg file so that we don't need long "https://........" appear everywhere.
@RackHD/corecommitters @iceiilin @pengz1

Set prefix as repo address to simplify ESXi boot.cfg design

---

static/schemas/2.0/user.2.0.json

In response to ODR-860: https://hwjiraprd01.corp.emc.com/browse/ODR-860
Made user role a requirement when creating a new user.
Also made Operator an accepted role type based on rackhd docs,
http://rackhd.readthedocs.io/en/latest/rackhd/authorization.html#built-in-roles
and role privileges in on-http,
https://github.com/RackHD/on-http/blob/master/lib/services/account-api-service.js#L62-L75

Made user role a requirement and added Operator to roles list

---

lib/api/1.1/northbound/templates.js
spec/lib/api/1.1/templates-spec.js

fix https://github.com/RackHD/RackHD/issues/430
templates.get() interface requires scope as a parameter. If it is not specified, this interface only returns the templates with "global" scope.
In templates/library API, add "scope" as a parameter when getting templates.
In templates/library/:id, add "?scope=xxx" to get a template for a specific scope, which is align with the behavior in API 2.0. If user doesn't use this query, the default scope is global.
@cgx027 @changev

fix issue#430 about templates api in version 1.1

---

data/templates/esx.rackhdcallback

Remove RackHD callback script after ESXi installation. 
Otherwise ESXi will try sending API to RackHD every time it boots, causing much longer boot time if disconnected from RackHD.
This script is called two times in ESXi installation workflow. Firstly in firstboot, and then in the final reboot for ssh validation, thus a tmp file (rackhd_callback) is created as a flag to signal it is called before so that this script could be deleted the second time it is called.
Putting this flag in /vmfs is because ESXi uses in-memory file system, and there is no method to persist user specific files in other directory of the OS. refer http://www.virtuallyghetto.com/2011/08/how-to-persist-configuration-changes-in.html 
@lanchongyizu

remove rackhd callback script after esxi installation

---

data/templates/centos-ks

- In a case of centos install it is almost impossible for the user to find out what the interface name would be ahead of time. ethx will not cut it as centos may use a different interface naming scheme.
The line below was added so that the interface name is forced to be <%=n.device%>
`echo "HWADDR=<%=n.hwaddr%>" >> /etc/sysconfig/network-scripts/ifcfg-<%=n.device%>`
See [https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Understanding_the_Device_Renaming_Procedure.html](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Understanding_the_Device_Renaming_Procedure.html) for refence.
- If the ipv6 or the ipv4 configurations are not specified set the interface for DHCP.

Ztip centos kickstart update

---

static/monorail-2.0.yaml

clean up descriptions and error codes in the yaml file
@RackHD/corecommitters @dalebremner @srinia6 @keedya @tannoa2 @uppalk1 @geoff-reid

correcting yaml cp errors

---

static/DSP8010_1.0.0/json-schema-oem/RackHD.BootImage.json
static/monorail-2.0.yaml

This is to fix the new issue that recorded in ODR905: https://hwjiraprd01.corp.emc.com/browse/ODR-905
The ESXi installation supports an additional parameter "esxSwitchName" in static network configuration, but the "additionalProperties: false" is set and thus cause the esxSwitchName cannot be specified.
@RackHD/corecommitters @zyoung51 @pengz1 @iceiilin @lanchongyizu
jenkins: depends on https://github.com/RackHD/on-tasks/pull/353

ODR905: add esxSwitchName (in networkDevices) support for ESXi installation

---

data/views/ibms.2.0.json
data/views/node.2.0.json
lib/api/1.1/northbound/nodes.js
lib/api/2.0/ibms.js
lib/fittings/rackhd_validator.js
lib/serializables/v1/ssh.js
lib/services/nodes-api-service.js
lib/services/swagger-api-service.js
spec/lib/api/1.1/nodes-spec.js
spec/lib/api/2.0/ibms-spec.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/serializables/v1/ssh-spec.js
static/monorail-2.0.yaml
static/schemas/ibms/ssh-ibm-service.json

This PR Jenkins:depends on https://github.com/RackHD/on-core/pull/222 and Jenkins:depends on RackHD/on-tasks#361
In this PR:
```
Move sshSettings from nodes.
Create /ibms and /ibms/{identifier} like the obms .
Backward compatible with 1.1 like obms.
Schema/view for ibms.
unit-test fix
```
@RackHD/corecommitters @dalebremner @brianparry @BillyAbildgaard @geoff-reid

Ssh obm service

---

static/monorail-2.0.yaml

Adding response type definition for https://github.com/RackHD/on-http/pull/511
@brianparry does this look right?

Add errors type to swagger ErrorResponse schema

---

data/templates/esx-ks
data/templates/esx.rackhdcallback

It's related with ODR-259.
create ssh keys for Esxi at startup since it can't be persistent.
@RackHD/corecommitters @panpan0000 @iceiilin

create ssh keys at startup for Esxi

---

lib/serializables/v1/ssh.js
spec/lib/serializables/v1/ssh-spec.js

Public key is required for ssh connection for Inband management, and private key is optional.
This is related with ODR-972.
@RackHD/corecommitters @panpan0000 @iceiilin @benbp

Add ssh public key for Inband management.

---

lib/services/auth-service.js

I tried to access API  without token or with a wrong token and just got an empty object.
Cause:
The returned info object is a list.
But the code uses it as a dictionary which contains "message".

return empty object when access api without token or with error token

---

data/templates/unattend_server2012.xml

@tannoa2 @srinia6 @dalebremner @geoff-reid @keedya

fixing ipv6 gateway

---

data/templates/unattend_server2012.xml

* Add firewallDisable to let ping function test the new static IP

Windows os regression script enhancement

---

data/templates/bootstrap.js

When we ask bootstrap.js to exit we pass the value as the `exit` member of the tasks structure. Problem is that bootstrap.js seems to expect it to be `exit.code`. I've fixed this defensively as I'm not sure if there are prior installations that expect the `exit.code` value.

Fix exit code handling in bootstrap.js

---

lib/services/nodes-api-service.js
lib/services/schema-api-service.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/services/nodes-api-service-spec.js
spec/lib/services/upnp-service-spec.js
static/monorail-2.0.yaml
static/schemas/2.0/node.2.0.json

This is a part of fix for https://github.com/RackHD/RackHD/issues/483
Root cause: After the obm is moved to a standalone model, we forget to add the obm setting while posting a new node, so some node catalog job will fail.
BTW: the unit-test error due to the node-cache is fixed as well in my PR.
@RackHD/corecommitters @iceiilin @cgx027 @pengz1 @manfrednde

Add obm setting while posting a new node

---

lib/services/profiles-api-service.js

Jenkins depends on: https://github.com/RackHD/on-core/pull/230 
on-core PR #230 fixed a typo on errors.js where InternalServerError should be a subclass of BaseError, thus InternalServerError should be called with a string parameter. 
In lib/services/profiles-api-service.js Lin 384, InternalServerError is mistakenly with an Error object. On-http unit test fails because of this. Here is the Jenkins log: http://rackhdci.lss.emc.com/job/on-http/2881/
Change parameter from Object to string.

Fix error where InternalServerError is called with a Error object

---

lib/api/1.1/northbound/workflows.js
lib/api/2.0/workflows.js

@RackHD/corecommitters 
New way to resolve: https://github.com/RackHD/RackHD/issues/241
This PR depends on: https://github.com/RackHD/on-core/pull/228
both PRs resolve: https://github.com/RackHD/RackHD/issues/417
this is the final PR to revert old (complex and overlapping) encryption of passwords to simply redact secret fields prior to the object being passed to the client.

added redactions to workflows GET by :id

---

data/templates/cloud-config.yaml

- Required for task driveId
- Adding  -v=dev:/dev to the docker run command

Mount host dev in the micro container

---

lib/api/redfish-1.0/account-service.js

Presently, redfish users can be created with any string given as their RoleId. This change ensures that users can only be made with known role values taken from getRoleByName()

Compare RoleId value to existing roles and only accepts known roles

---

lib/api/2.0/tasks.js
spec/lib/api/2.0/tasks-spec.js

/tasks/{identifier} was returning 204 whenever a task for searched for and not found or when a bad task was provided. By design, this should be returning 404 as specified in monorail-2.0.yaml. What has been removed resolves this.

RAC-2044/ODR-952 Removed 204 response code to make congruent with swagger definition file

---

data/templates/set_interfaces.py

This script iterates through all the interfaces in the microkernel and sets their default IP address, netmask, gateway. Once all the interfaces are set, then the script makes sure that all interfaces are up.
Referencing this pull request: 
https://github.com/RackHD/on-tasks/pull/367

Script to enable interfaces inorder to send/receive LLDP

---

data/templates/cisco-catalog-config.py

this command `cli('show startup-config')` returns the output as a string  so using `[0]` will only get the first character.

Fixed returned value of cli command in catalog config

---

extra/make-deb.sh
static/monorail-2.0.yaml
static/redfish.yaml

Travis will now use the version number from the yaml file when generating the pypi client libraries.
@brianparry @anhou @yyscamper @panpan0000

add version to python packages

---

lib/services/profiles-api-service.js
spec/lib/services/profiles-api-service-spec.js

RAC-2020 Provide capability to run configurable discovery workflow https://rackhd.atlassian.net/browse/RAC-2020

Graph config

---

data/profiles/install-centos.ipxe
data/templates/secure_erase.py
lib/api/2.0/notification.js
lib/services/common-api-presenter.js
lib/services/swagger-api-service.js
spec/lib/api/2.0/notification-spec.js

* This PR is to address Felix's comments on ipxe progress
API,_getActiveTask function and progress data type.
* Code is udpated based on comments.
* No feature impacted.

 Refactor progress code

---

lib/services/profiles-api-service.js
spec/lib/services/profiles-api-service-spec.js

Add a new option in the config file to allow user to skip the generation of pollers on a compute node

Add skipPollerOption to determine creating or skipping 

---

.travis.yml
extra/make-deb.sh

rework of PR https://github.com/RackHD/on-http/pull/549
**Highlight**
the building of swagger python client  package : on-http-api1.1,  on-http-api2.0 ,  on-http-redfish-1.0 still being kept in TravisCI , since Jenkins hasn't covered it yet.
so the ```./extra/make-deb.sh``` & ```.bintray-deb.json``` still there.
**Background**
https://groups.google.com/forum/#!topic/rackhd/MoES4tSsMKk
Jenkins upload package will be like ```1.1-1-20161205UTC-627fbb3  ```
and Travis version will be like ```1.1-1master-20160930100654Z1```, which always newer than Jenkins' publish packages. so we  will have to disable Travis uploading.
moreover, Bintray has stopped Travis CI to upload deb:
```Bintray response: 403 Forbidden. Version 'master' has been published more than 180 days ago and can no longer be …
```

Stop TravisCI to upload deb to Bintray on-http

---

.travis.yml

Oops,  my PR https://github.com/RackHD/on-http/pull/556 has wrongly remove the swagger python deb build .
so this PR added it back ..
@brianparry @geoff-reid

add swagger python-client deb build back

---

data/templates/cisco-catalog-version.py

that json encoding escapes on and renders incorrectly.
This removes those characters and allows correct encoding.
Signed-off-by: Ethan Kaley <ethan.kaley@emc.com>

Cisco Version Header string contains extra escape characters

---

data/templates/remove_bmc_credentials.sh
data/templates/set_bmc_credentials.sh
lib/services/profiles-api-service.js
spec/lib/services/profiles-api-service-spec.js

- Set bmc credentials used to get user count of enabled bmc users
It should get the toal nb of bmc users
- Remove users fails the user list command; Added logic to get the open channel nb
- Migrate set bms credentials from discovery graph to Discovery-sku-graph
in discovery graph, group label is set in bootstrap
and it overides the tasks properties
Fix for https://github.com/RackHD/RackHD/issues/602
depends on: https://github.com/RackHD/on-taskgraph/pull/210

Bugfix for set bmc credentials

---

data/templates/unattend_server2012.xml

This is to fix the failure with windows OS install, https://rackhd.atlassian.net/browse/RAC-4035
@RackHD/corecommitters @tannoa2 @keedya @uppalk1

prevent render error if networkDevices is not defined

---

data/templates/esx-ks

Reverts RackHD/on-http#497
Some problems for this PR, and it caused regression test failure http://rackhdci.lss.emc.com/job/Continuous-Test/job/OS-Install-Jobs/job/ESXi-6.0/321/, I confirmed with @lanchongyizu about these problems
1. call /notifications URL is essential, cannot be removed.
2. postlookup() is out of date, currently, we don't need this function, don't need to add it back to previous status
3. rackhdCallbackScript will be rendered once esx-ks is downloaded.
@nucklehead Because this PR will cause OS installation regression test failure, I'll revert this PR, when you have more time, you could address these problems above and submit another PR, If you don't have more time, we could help pick useful things in this PR and submit another PR.
@RackHD/corecommitters because this PR …

Revert "Ztip esx kickstart update"

---

lib/api/1.1/northbound/router.js
lib/api/1.1/southbound/router.js

Add a Deprecation warning header to north/south-bound 1.1 API.
@RackHD/corecommitters @RackHD/veyron

Add Deprecation Warning Header to 1.1 northbound/southbound router

---

lib/api/1.1/northbound/nodes.js
lib/services/nodes-api-service.js
spec/lib/api/1.1/nodes-spec.js
spec/lib/services/nodes-api-service-spec.js
static/schemas/2.0/node.2.0.json

changing post node so it doesn't use old snmpSettings from node 
@RackHD/veyron

updating postNode w/ new snmpSettings

---

lib/api/redfish-1.0/managers.js

Fix for RAC-72. Now return data, even when no nodes are discovered instead of throwing an error.
@RackHD/corecommitters @RackHD/veyron

Fix redfish/manager/id to return data, when no nodes are discovered

---

data/profiles/install-centos.ipxe
data/templates/centos-ks
lib/api/2.0/notification.js
lib/services/common-api-presenter.js
spec/lib/api/2.0/notification-spec.js
static/monorail-2.0-sb.yaml

1. Directly reference the milestone definition rather than the raw value.
2. Change all progress notification to be sent via URI /notification/progress
3. Explain the strange implemention for GET /notification/progress
4. Remove totalSteps/currentStep, always use the typic variable maximum/value
jenkins: depends on https://github.com/RackHD/on-tasks/pull/407
@pengz1 @lanchongyizu

Refactor OS installation progress

---

data/profiles/install-coreos.ipxe
data/profiles/install-esx.ipxe
data/profiles/install-photon-os.ipxe
data/profiles/install-suse.ipxe
data/profiles/install-ubuntu.ipxe
data/templates/esx-ks
data/templates/install-coreos.sh
data/templates/install-photon/photon-os-ks
data/templates/install-ubuntu/ubuntu-preseed
data/templates/suse-autoinst.xml
lib/services/notification-api-service.js
spec/lib/services/notification-api-service-spec.js

Inject progress milestones for ESXi/Ubuntu/SUSE/CoreOS/PhotonOS.
Different OS exports different injectable point where we can send a http request to notify the current installation stage, so the milestone definition varies on different OS.
I have done at least 3 times testing for each OS for make sure the OS installation has not been broken and the output progress data is correct.
Story links:
- https://rackhd.atlassian.net/browse/RAC-3920
- https://rackhd.atlassian.net/browse/RAC-3919
Thanks @lanchongyizu to help implement the progress for Windows OS ( see PRs https://github.com/RackHD/on-http/pull/593 and https://github.com/RackHD/on-tasks/pull/409 )
jenkins: depends on https://github.com/RackHD/on-tasks/pull/410
@pengz1 @lanchongyizu @anhou @iceiilin

add progress milestones for ESXi/Ubuntu/SUSE/CoreOS/PhotonOS

---

static/schemas/2.0/node.2.0.json

identifiers property was in the node schema twice
@RackHD/veyron

removing duplicate property

---

static/monorail-2.0.yaml

The $ref under HooksPost was causing the swagger-ui crash.
@RackHD/corecommitters @RackHD/veyron

Fix bug  introduced by hook-schema that breaks swagger-ui

---

lib/services/hooks-api-service.js
spec/lib/services/hooks-api-service-spec.js

Schema URL validation doesn't work, add url validation code in hook-api

Validate url for webhook

---

data/templates/install-photon/photon-os-ks

fix https://rackhd.atlassian.net/browse/RAC-4324, which complains inproper UI display after installing Photon OS using full payload in https://github.com/RackHD/RackHD/blob/master/example/samples/install_photon_os_payload_full.json
From KS file sample provided by Photon, the swap partition is the last item in the "partition" field. This PR modify the rendering rule in ks template to align with it and pass the test.

modify photon ks file to put swap partition as the last item

---

lib/api/2.0/nodes.js
lib/services/workflow-api-service.js
spec/lib/api/2.0/nodes-spec.js

Reverts RackHD/on-http#551 
CI Test failure http://rackhdci.lss.emc.com/job/ContinuousFunctionTest/192/
@lacarb you could resubmit another PR and also include related test cases fix. 

Revert "Rac 1984 node/id/workflow returns appropriate response codes"

---

lib/api/2.0/users.js

Extend the Localhost Exception, to allow backdoor access to create an Administrator account, when there are no "Adminstrator" in the collection.

Allow backdoor process, to create Administrator user

---

lib/services/profiles-api-service.js
spec/lib/api/2.0/profiles-spec.js
spec/lib/services/profiles-api-service-spec.js

there's many long and duplicated taskgraphInstance log when analysis  masterci log. only show graph instanceId that it could match with previous full graph log http://rackhdci.lss.emc.com/job/MasterCI/67/artifact/Install-ESXI-6.0/vagrant.log   
@RackHD/corecommitters @iceiilin @yyscamper @changev

Refine get profile log

---

static/monorail-2.0.yaml

This PR:
1. Addresses RAC-4622, to update/correct schema.
2. Reference them in responses. 
The original issue was seen while generating client libraries in GO/JAVA, where return types are all list, 
and the user has to manually parse the returned data. This addresses that.
3. Fix few responses return type, array of object VS just objects.
@RackHD/corecommitters @jasl8r

Add/update schemas, and reference them in response object

---

README.md
extra/make-client.sh
package.json

- creating a script to generate client libraries for go, java, and python
- updating on-http readme to remove 1.1 API references
- updating package.json to remove 1.1 documentation generation. added new client command used to generate client libraries
@RackHD/veyron

creating script to make client libs

---

Dockerfile

removing apidoc command.  This was used to generate 1.1 documentation and since we have swagger-ui it seems to add no additional value by also generating this documentation.
@RackHD/veyron

removing apidoc

---

static/monorail-2.0.yaml

the swagger-ui shows { "role": "string", "username": "string"} instead of { "role": "string", "password": "string"} for input. the username is already a required field.
underneath, the get_user_obj does not provide a password for modifyUser() in lib/api/2.0/user.js. 
fix: created a patch_user_obj with role and password data.

RAC-4558: patch users{name} does not accept password changes

---

lib/api/2.0/nodes.js
spec/lib/api/2.0/nodes-spec.js

Follow up to this PR which used to be green but broke the pipeline when it was merged a few days later - https://github.com/RackHD/on-http/pull/551
Investigating what went wrong.

Rac 1984 redo - node/id/workflow fix after revert

---

lib/api/2.0/profiles.js
spec/lib/api/2.0/profiles-spec.js

Prioritize "X-Real-IP" for switch getting profile to support proxy.

 Add proxy support for switch

---

lib/services/notification-api-service.js
spec/lib/api/2.0/notification-spec.js

Existing progress data pre-validation will reject 0 value, this is not expected.
This PR enhances progress data pre-validation and pack them in a Promise.try.
Also negative and boundary tests are added.

 Fix-notification-progress-data-pre-validation-error

---

data/templates/secure_erase.py

Changes include:
1. Existing secure_erase.py use a progress notification payload like:
{"taskID": xxx, "progress": {"value":0, "maximum"}}
Our latest progress notification payload require payload to be like:
{"taskID": xxx, "value":0, "maximum"}
Update secure_erase.py to adopt latest payload format.
2. Set default secure erase in Progress class, otherwise progress notification may not posted to RackHD
3. Other changes include: 
Change Progress class to new type;
Correct Message to message;
Set default pass_count to 1.

 Update secure erase to use latest progress notification api

---

lib/api/2.0/schemas2.js
spec/lib/api/2.0/schemas-spec.js
static/monorail-2.0.yaml

Changelog:
- The task schema identifier is changed to use task's injectableName rather than filename, since the built-in schema doesn't have a filename
- GET /schemas/tasks will return the list of task injectableNames
- The `resolved` flag is removed in GET /schemas/tasks/:identifier since now the returned schema is always resolved. The unresolved version doesn't conform to the JSON schema standard, so it is removed.
@anhou @iceiilin @pengz1 @lanchongyizu @brianparry

Change /schemas/tasks API implementation according to new task schema design

---

data/templates/esx-ks

Recreating vmk#N also recreates MAC Address for it, which will change the vmk#N's MAC Address(same as vmnic#N) when setting static IP. 
This behavior should be avoided.  
@RackHD/corecommitters @panpan0000 @zyoung51

Keep the MAC Address if possible when link it to the new portgroup

---

lib/fittings/rackhd_validator.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/api/2.0/obms-spec.js
static/monorail-2.0.yaml
static/schemas/obms/amt-obm-service.json
static/schemas/obms/apc-obm-service.json
static/schemas/obms/ipmi-obm-service.json
static/schemas/obms/noop-obm-service.json
static/schemas/obms/panduit-obm-service.json
static/schemas/obms/raritan-obm-service.json
static/schemas/obms/redfish-obm-service.json
static/schemas/obms/servertech-obm-service.json
static/schemas/obms/snmp-obm-service.json
static/schemas/obms/vbox-obm-service.json
static/schemas/obms/vmrun-obm-service.json

Linked to story RAC-4766. Make nodeId optional when doing a PATCH, and set additional properties to false.

PATCH obms with only service and config as required properties

---

data/templates/esx-boot-cfg
data/templates/esx-ks

In many rack mount servers or customized servers, there is no monitor connected, UART port are usually used as console. VMware ESXi use VGA card as console. User need pass VM kernel To support this use, I add three options: "gdbPort","logPort","debugLogToSerial".
[VMware ESXi referrence](https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.install.doc_50%2FGUID-C65306C0-DA37-4F45-8A50-31F8D109BB1D.html])
To support this , 'on-http/data/templates/esx-boot-cfg', 'on-http/data/templates/esx-ks'(This PR) and 'on-tasks/lib/task-data/tasks/install-esx.js'(in another PR for on-tasks) are changed.
The default value of those options keep console in VGA as it does before. User can customize the console redirect setting in the OS bootstrapping payload.
Jenkins depends on …

Add options to allow console redirect in ESXi bootstrap

---

lib/api/2.0/config.js
static/monorail-2.0.yaml

@danbmckay and I added PUT rest call which essentially behaves as a PATCH. We are using swagger codegen and it doesnt support PATCH unless we have a POST call which /config doesn't have.
Shown below is the generated code from swagger codegen:
```
if ("GET".equals(method)) {
response = invocationBuilder.get();
} else if ("POST".equals(method)) {
response = invocationBuilder.post(entity);
} else if ("PUT".equals(method)) {
response = invocationBuilder.put(entity);
} else if ("DELETE".equals(method)) {
response = invocationBuilder.delete();
} else if ("PATCH".equals(method)) {
response = invocationBuilder.header("X-HTTP-Method-Override", "PATCH").post(entity);
} else {
throw new ApiException(500, "unknown method type " + method);
}
```

Added PUT to config

---

lib/services/nodes-api-service.js
spec/lib/services/nodes-api-service-spec.js

Fix https://rackhd.atlassian.net/browse/RAC-4805
jenkins: depends on https://github.com/RackHD/on-core/pull/278
Enclosure node will be updated when deleting compute node.
Find enclosure -> modify -> write
Used:
* find enclosure, delete the compute id in targets and get a new  enclosure [object], then ```update``` enclosure with this [object].
* this is not atomic
Now:
* find enclosure, use ```findAndModify``` to delete compute id in its target. If target = [], use ```findAndModify``` to delete the relation too
* this is atomic

keep data consistency in enclosure update

---

static/monorail-2.0.yaml

updating client library generation to reflect the view used for the tags property of a node
@RackHD/veyron @king-jam

client libs tags fix

---

data/views/redfish-1.0/redfish.1.0.0.bios.1.0.0.json
data/views/redfish-1.0/redfish.1.0.0.bios.1.0.0.settings.json
data/views/redfish-1.0/redfish.1.0.0.computersystem.1.0.0.json
data/views/redfish-1.0/wsman.1.0.0.computersystem.1.0.0.json
lib/api/redfish-1.0/systems.js
spec/lib/api/redfish-1.0/system-spec.js
static/redfish.yaml

Added the following endpoints:
GET /redfish/v1/Systems/{identifier}/Bios
GET /redfish/v1/Systems/{identifier}/Bios/Settings
PATCH /redfish/v1/Systems/{identifier}/Bios/Settings
- This implements redfish systems bios settings for Dell
nodes only.
- Fix patch to return 202 http status on success.
- Added system/bios tests for Dell and non-Dell systems.

RAC-4177, RAC-4909, RAC-4901

---

data/views/redfish-1.0/redfish.1.0.0.ethernetinterface.1.0.0.json
data/views/redfish-1.0/redfish.1.0.0.ethernetinterfacecollection.json
lib/api/redfish-1.0/managers.js
lib/api/redfish-1.0/systems.js
spec/lib/api/redfish-1.0/system-spec.js
static/redfish.yaml

* Add support for the following API endpoints:
GET /redfish/v1/Systems/identifier/EthernetInterfaces
GET /redfish/v1/Systems/identifier/EthernetInterfaces/index
* Add redfish 2016.3 schema into redfish.yaml definition
* npm tests added
* Fix manager.js and systems.js to share ethernet interface
rendering files.  Pass through necessary context info
in options block.

RAC-4172 GET Systems/EthernetInterfaces

---

lib/services/profiles-api-service.js
spec/lib/services/profiles-api-service-spec.js

- Adding a new flag in the config file skipResetPostDiscovery

Make skip reboot after discovery optional:

---

lib/services/workflow-api-service.js

This PR is to remove the graph length( 0 or 1) check( so that we have able to execute a graph that have a graph within it. 
The rediscovery graph length is 2 and it will fail with the check is place.

RAC-5241 Can't perform node rediscovery using post /workflows O

---

lib/api/2.0/nodes.js
lib/services/nodes-api-service.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/services/nodes-api-service-spec.js

jenkins: depends on https://github.com/RackHD/on-core/pull/280
Modified 
```
_addRelation
_removeRelation
EditRelation
```
to keep data consistency

keep data consistency when add realtions

---

data/views/redfish-1.0/redfish.1.0.0.softwareinventorycollection.json
lib/api/redfish-1.0/update-service.js
spec/lib/api/redfish-1.0/update-service-spec.js
static/redfish.yaml

Add UpdateService/SoftwareInventory route, and tweaked existing code to make it common for both Firmware/Software, and RACADM catalog has both "FIRMWARE" and "APPLICATION" type of components.
@dalebremner @RackHD/corecommitters

Create SoftwareInventory route, tweak existing Firmware code/view, unit-test fixes

---

spec/lib/api/2.0/users-spec.js
static/monorail-2.0.yaml
static/redfish.yaml

Adding bare minimum account username complexity checking on account creation for both APIs.
As it stands now, accounts can be created with a single space, for example.
Change necessitates that usernames begin with a letter, followed by any number of letters, numbers, hyphens, periods, and underscores.

RAC-4625: adding username complexity checking on account create

---

lib/api/2.0/users.js
lib/api/redfish-1.0/account-service.js
spec/lib/api/2.0/users-spec.js
static/monorail-2.0.yaml
static/redfish.yaml

Currently we are returning 401 Unauthorized responses when attempting to create an account user that already exists. This change returns a 409 'user already exists' message instead for both Redfish and v2.0 APIs.

RAC-4626: returning correct resp code for duplicate account

---

static/monorail-2.0-sb.yaml

Bring missed api "getting files/<name>" and "files/<name>/md5" back in southbound API. It is used in firmware update feature in skupack, where users could use workflow payload to tell the node fetching image file from files/ API.

bring missed api "files/<name>" and "files/<name>/md5" back to southbound api

---

lib/api/2.0/notification.js
spec/lib/api/2.0/notification-spec.js

1. Why we need to get node IP:
RackHD needs to access http service on a compute node in  diag related tasks with node IP. The normal way to get IP/MAC from lookups can't work because lookups may contain more than one IPs that are legacy and incorrect. 
2. How this feature is implemented:
Retried node IP in on-http and add IP into notification AMQP messages => Install OS job retrieve IP from AMQP message and add it to graph context => following jobs to retrieve IP from graph context.
Jenkins depends on: https://github.com/RackHD/on-tasks/pull/470

 Add IP address information to notification events

---

data/views/redfish-1.0/redfish.1.0.0.logentry.1.0.0.json
lib/api/redfish-1.0/systems.js
spec/lib/api/redfish-1.0/system-spec.js

* In redfish logentry.1.0.0.json, bypass "Created' keyword if timestamp is null
* In systems.js, skip time and date processing if date is ""
* Create test to validate empty date and time processing

RAC-5414 - LogServices/sel/Entries "Cannot read property '3' of null"

---

static/redfishMetadata.xml

Need to fix a typo in redfishMetadata.xml file for compliance testing.

RAC-5629 - Fix typo in reference for MessageRegistry to be v1_0_0.

---

.travis.yml

Fix RAC-5316: Travis CI: failed to build debian packages
Error message:
`+debuild --no-lintian --no-tgz-check -us -uc
debuild: fatal error at line 948:
problem running fakeroot: either install the fakeroot package,
use a -r option to select another root command program to use or
run me as root!`
The PR: install fakeroot for debuild to fix the issue.
@anhou @iceiilin

[RAC5316]Travis CI: failed to build debian packages

---

.travis.yml

Recently, TravisCI has an upgrade from precise to higher ubuntu distribution. mongo verison is also upgraded, add `dist: precise` to make TravisCI still use previous ubuntu precise version to let it pass. it's only a temporary method.  later, we'll submit PR to all repos to fix the compatibility problem.

Fix TravisCI unittest failure

---

lib/services/http-service.js

Before the code change, on-http.log has a whole bunch of information that doesn't help. To help the developers grasp important information sooner, remove the unnecessary information. For example, when executing a curl command that fails, the log only shows the information of "message", "status" and "uuid".
This is to solve  the issue in:
https://rackhd.atlassian.net/browse/RAC-5457
@iceiilin @anhou @pengz1

Refine error log when http request failure in on-http.log

---

lib/services/wsman-service.js
spec/lib/api/redfish-1.0/system-spec.js

* Dell vs non-dell is not handled quite right. The wsman.isDellSystem call
should be allowed to succeed or fail based on the result of getNodeById.
* Default resolve statements mask various blocks of code.
* Add some consistency to the use of node ids. Reference object ids
when possible instead of writing duplicate ids.
* Add consistency to sel and lc case

RAC-5786 - Normalization of system-spec.js

---

.gitignore

**Background**
Previously, static/files/ is ignored by .gitignore, but npm publish will match the ignore rule in .gitignore if .npmignore file is not specified. So after we install on-http by using npm, a _static/files folder not found error_ will occur when trying to upload a file to on-http.
**Solution**
In order to solve this problem, we can ignore all the files under static/files folder except the .gitkeep file by changing the .gitignore file.

RAC-4984 [cookie]npm install on-http missing static/files folder

---

data/views/redfish-1.0/redfish.1.0.0.manager.1.0.0.json

NetworkProtocols ref link has been set in managers.
New Output:
'''
{
"@odata.context": "/redfish/v1/$metadata#Manager.Manager",
"@odata.id": "/redfish/v1/Managers/RackHD",
"@odata.type": "#Manager.v1_0_0.Manager",
"Oem": {},
"Id": "RackHD",
"Name": "Manager",
"ManagerType": "ManagementController",
"Links": {
"ManagerForServers@odata.count": 4,
"ManagerForServers": [
{
"@odata.id": "/redfish/v1/Systems/5988b760df3287057100f6b3"
},
{
"@odata.id": "/redfish/v1/Systems/5988b763df3287057100f6b4"
},
{
"@odata.id": "/redfish/v1/Systems/5988b795df3287057100f6b5"
},
{
"@odata.id": "/redfish/v1/Systems/5988bd64df3287057100f6b6"
}
],
"ManagerForChassis@odata.count": 4,
"ManagerForChassis": [
{
"@odata.id": "/redfish/v1/Chassis/5988b90aa13c6c197227e0a7"
},
{
"@odata.id": …

RAC-5746 Network protocol conformance

---

data/templates/megaraid-config.sh

Enhance the existing script that meets CPSD's FRU replacement guidelines. Works on Quanta and Dell nodes with appropriate payload.
Example payload for quanta:
{
"options": {
"config-raid":{
"ssdStoragePoolArr":[],
"ssdCacheCadeArr":[
{
"enclosure": 252,
"type": "raid0",
"drives":"[0]"
}
],
"controller": 0,
"path":"/opt/MegaRAID/storcli/storcli64",
"hddArr":[
{
"enclosure": 252,
"type": "raid0",
"drives":"[1]"
},
{
"enclosure": 252,
"type": "raid1",
"drives":"[4,5]"
}
]
}
}
}

Raid configuration support

---

data/views/redfish-1.0/redfish.1.0.0.ethernetinterface.1.0.0.json
lib/api/redfish-1.0/systems.js
spec/lib/api/redfish-1.0/system-spec.js

* Correct issues with dictionaries that use null as a value
* Do not display LinkStatus if value is null
* Add test to validate

RAC-5799 - Pv4, IPv6 system IPs are not populated

---

HWIMO-TEST

The unit test depends on mongodb and rabbitmq.
The PR enhances the script HWIMO-TEST to run unit test with checking and setup dependencies.
@anhou @iceiilin @lanchongyizu @panpan0000

RAC5843: enhance HWIMO-TEST to handle the dependencies

---

data/views/redfish-1.0/redfish.1.0.0.ethernetinterface.1.0.0.json

* removed quotes that forced a string

rac-5909 - ipv6 PrefixLength returned as string instead of int

---

data/views/redfish-1.0/ucs.1.0.0.processorcollection.json
lib/api/redfish-1.0/systems.js
lib/services/redfish-validator-service.js
spec/lib/api/redfish-1.0/system-spec.js
spec/lib/services/redfish-validator-service-spec.js

Background
To enable redfish API data access with UCS.
Details
1. Implemented details to identify Dell/Cisco and other hardware platforms
2. Implement /Systems/identifier/Processors API for UCS
Paired with: @bbcyyb
@anhou @iceiilin @yaolingling @mcgG @larry-dean

 Add redfish /Systems/identifier/Processors API for UCS

---

data/views/redfish-1.0/redfish.2016.3.computersystem.1.3.0.json
data/views/redfish-1.0/wsman.1.0.0.computersystem.1.0.0.json

* fixed in two views a missing '=' in '<%='

RAC-5998: Dell redfish systems/identifier returns "" for hostName

---

extra/make-docs.sh

the swaggerdoc script was removed in in package.json in commit 9ee580308264f25ebfbf8af1c2577f195201e1c6
but people forgot to remove it in TravisCI scripts.

remove the swaggerdoc step in TravisCI

---

HWIMO-TEST

Failed to run script "HWIMO-TEST"  as user root.
Cause: 
```npm install``` does not run scripts specified in package.json files as user root.
That causes the failure of unit test.
Because the file may be run in docker, we need to fix the issue.
Solution:
1. Run ```npm install --unsate-perm```
2. Run the scripts specified in package.json files after ```npm install```. That brings duplicate between package.json and HWIMO-TEST.
@geoff-reid @anhou @iceiilin @keedya @panpan0000 Looking forward to your comments!

Fix: failed to run unit test as user root

---

data/views/redfish-1.0/ucs.1.0.0.processor.1.0.0.json
lib/api/redfish-1.0/systems.js
spec/lib/api/redfish-1.0/system-spec.js

**Background**
---
Previous api didn't support to retrieve processor info from UCS.
----
Details
---
1. Implemented /systems/{identifier}/Processors/{socketId} API to get Dell/Cisco/Others Processors information
2. Implemented details to identify Dell/Cisco and other hardware platforms
@iceiilin @anhou @pengz1 @yaolingling

RAC-5098 GET /Systems/{identifier}/Processors/{socket} implementation for redfish api

---

data/templates/get_driveid.js
spec/data/templates/get_driveid-spec.js

The ESXi use their own method to generate a identity for the hard drives they found in the system. We use this script run microkernel to gernerate the same ID using the same algorithm as vmware. However in some latest server, we found some SSD's ESXi ID is wrong in RackHD.  It is because RackHD will use WWID to overide the SATA name if it is available. But in fact, ESXi use SATA name to identify this kind of SATA drive.
Revert the overide process. Use SATA name as ESXi  ID if drive have both SATA name and WWID.
Validated PASS on EMC platforms.
@pengz1 @iceiilin

RAC-5001 Change WWID to SATA name for ESXi SATA drive ID

---

data/views/redfish-1.0/ucs.1.0.0.simplestorage.1.1.1.json
lib/api/redfish-1.0/systems.js
spec/lib/api/redfish-1.0/system-spec.js

The UCS redfish api 'GET /Systems/{identifier}/SimpleStorage/{index}' is broken. Try to fix it.
1. Execute the command to get simpleStorage. The result is shown in the screenshot.
curl localhost:8080/redfish/v1/Systems/59a66a30e466b6e2457f0f01/SimpleStorage/SAS_01_00_0_1 | jq '.'
@iceiilin @pengz1 @anhou @mcgG

RAC-5100 : UCS redfsh is broke GET GET /Systems/{identifier}/SimpleStorage/{index}	

---

lib/api/redfish-1.0/systems.js

No need to iterate over (and return) obm settings when the
/redfish/v1/managers query ignores the indexes anyway.
Redfish ServiceValidator found index issues where the ManagedBy
resources were not valid query urls.

RAC-6084: Remove .0, .1 indexes from system linkages. (ie ManagedBy)

---

lib/services/profiles-api-service.js
lib/services/swagger-api-service.js
spec/lib/api/2.0/profiles-spec.js
spec/lib/services/profiles-api-service-spec.js

Fix https://rackhd.atlassian.net/browse/RAC-5768
The solution is remove lookup for macAddress when call /profiles?macs&&ips.

remove lookup for macAddress when call /profiles?macs&&ips

---

lib/services/redfish-api-service.js
spec/lib/services/redfish-api-service-spec.js

Background
redfish-validator-service.js uses an injectable name Http.Api.Services.Redfish, this is a little confusing. We should align filename with injectable name
Details:
Change redfish-validator-service.js  filename to redfish-validator-service.js
Change redfish-validator-service-spec.js  filename to redfish-validator-service-spec.js
Modified related variables and description in the two documents

 Change redfish-validator-service.js  filename to align with injector name

---

data/templates/get_driveid.js
spec/data/templates/get_driveid-spec.js

we found there will be an waterline validation error when driveIds.length==0 as below and task will fail
Error (E_VALIDATION) :: 1 attribute is invalid
at WLValidationError.WLError (/var/renasar/on-taskgraph/node_modules/on-core/node_modules/waterline/lib/waterline/error/WLError.js:26:15)
So we need to add something to driveIds to avoid the validation error, empty json {} makes sense.

waterline validation error when driveIds.length==0

---

HWIMO-TEST

Background
Mongo daemon command changed form 'mongodb' to 'mongod' after MongDB
2.6, this change is to accommodate both commands
Details:
Change mongo service command in HWIMO-TEST

 Accommodate mongodb and mongod in HWIMO

---

data/templates/centos-ks

removed the network option to address issues being seen in baremetal nodes.
The network port is not always coming up in time to allow selection of which interface to start the kickstart on.
Paired with Manfred on this update.  Tested against physical bare-metal stack with Quantas.
@manfrednde 
@keedya

RAC-6012 - address CentOS os install 360000ms timeouts on physical hardware

---

lib/api/redfish-1.0/update-service.js
package.json
spec/lib/api/redfish-1.0/update-service-spec.js

**Background**
Based on the preceding investigation work, start to port redfish get inventory underlying implementation from Racadm with WSMAN API.
**Details**
1. Replaced the RACADM catalog dependencies with WSMAN inventory catalog while getting FW/SW inventories;
2. Fixed unit test after the above modifications
**Reviewer**
@leoyjchang @nortonluo @lanchongyizu @yaolingling @anhou

[RAC-6211] Port Redfish Get Inventory feature underlying implementation from Racadm to WSMAN

---

lib/services/rest-api-service.js
package.json
spec/lib/services/hooks-api-service-spec.js
spec/lib/services/nodes-api-service-spec.js
spec/lib/services/rest-api-service-spec.js

**Background**
----
Currently, unit test will fail in Nodejs 6 and Nodejs 8.
[https://rackhd.atlassian.net/browse/RAC-6232](https://rackhd.atlassian.net/browse/RAC-6232)
**AC**:
- Paired with @PengTian0 
- Fix nodejs6 unit test failures in local machine
- Don’t break nodejs 4 unit test
- Pilot run in travisci environment(don’t commit the fix, because further FIT test should pass before submitting
**Detail**
----
About case Http.Server rest().should 500 if a deserializer returns a rejected promise (from Mocha Tests)
`
AssertionError: expected 'err.toString(...).contains is not a function' to equal 'deserializer reject!'
at spec/lib/services/rest-api-service-spec.js:418:31
at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
at Test.assert …

[RAC-6232]Node 6/8 unit test fix

---

lib/api/2.0/callback.js
lib/services/callback-api-service.js
spec/lib/api/2.0/callback-spec.js
static/monorail-2.0-sb.yaml

*Background*
UCSM http response is slower than RackHD in some cases and will lead to RackHD fails to get data from UCSM via HTTP. Thus in ucs-service we implemented asynchronous API to avoid this and data will be post back to RackHD via a callback API.
*Details*
- A new API /ucsCallback is create with POST method
- Unit test is included.
Paired with: @bbcyyb
@anhou @bbcyyb

 Implement ucsCallback API

---

.travis.yml

Enable node8 unit-test in travis-ci, failure is allowed

Enable node8 unit-test in travis-ci

---

spec/lib/services/hooks-api-service-spec.js
spec/lib/services/notification-api-service-spec.js

RAC:  [https://rackhd.atlassian.net/browse/RAC-5743](https://rackhd.atlassian.net/browse/RAC-5743)
----
Paired with @PengTian0 
Using both `return promise` and `done()` in async unit test case will cause following error:
`Resolution method is overspecified. Specify a callback *or* return a Promise; not both.`
According to Mocha's [official site](http://mochajs.org/):
`In Mocha v3.0.0 and newer, returning a Promise and calling done() will result in an exception`
**Solution**
----
Only call done() instead of return a promise in all async unit test cases.
@PengTian0 @pengz1 @anhou @iceiilin @bbcyyb

Unit test fix for mocha update

---

lib/api/redfish-1.0/systems.js
spec/lib/api/redfish-1.0/system-spec.js

**Background**
Based on the preceding investigation work ( https://rackhd.atlassian.net/browse/RAC-6175 ), I could start to port redfish Secure Boot underlying implementation from Racadm (if any) with WSMAN API.
https://rackhd.atlassian.net/browse/RAC-6215
**Done**
Port Redfish Secure Boot feature underlying implementation from Racadm to WSMAN
**Reviewers**
@RackHD/corecommitters @nortonluo @yaolingling

Port Redfish Secure Boot feature underlying implementation from Racadm to WSMAN

---

lib/api/redfish-1.0/systems.js
spec/lib/api/redfish-1.0/system-spec.js

**Backgroud**
The response for `POST /redfish/v1/Systems/{identifier}/SecureBoot` should be
```
{
"@odata.id": "string"
}
```
instead of
```
{
"Message": "Successfully Completed Request"
}
```
**Done**
1) Update the reponse in redfish API for setSecureBoot
2) refine the code
**Reviewers**
@RackHD/corecommitters @nortonluo

Update the reponse in redfish API for setSecureBoot

---

lib/api/redfish-1.0/systems.js
static/redfish.yaml

**Background**
Based on the previous investigation result, develop to port Graph.Dell.Racadm.ResetComponents and /Systems/{identifier}/Bios.ResetBios to use WSMAN API.
https://rackhd.atlassian.net/browse/RAC-6481
**Done**
update resetSystemBios to use Graph.Dell.Wsman.Reset.Components
@RackHD/corecommitters @nortonluo

update resetSystemBios to use Graph.Dell.Wsman.Reset.Components

---

lib/api/redfish-1.0/update-service.js
spec/lib/api/redfish-1.0/update-service-spec.js

**Background**
Our target is to replace all the RACADM dependencies with WSMAN in RackHD features. This task aims to replace RACADM with WSMAN graph to update single firmware.
**Details**
In on-http repo, now we call WSMAN single firmware update graph instead of RACADM, and ImageURI in payload should be assigned with http/https web URI.
1. Replaced RACADM reference with WSMAN in update-service.js.
2. Fixed UT according to modifications.
depends on: https://github.com/RackHD/on-taskgraph/pull/336 https://github.com/RackHD/on-tasks/pull/561
**Reviewer**
@lanchongyizu @yaolingling @nortonluo @leoyjchang

[RAC-6366] Port Firmware Update Redfish API to use WSMAN graph

---

data/views/redfish-1.0/redfish.1.0.0.chassiscollection.json
data/views/redfish-1.0/redfish.1.0.0.computersystemcollection.json
lib/api/redfish-1.0/chassis.js
lib/api/redfish-1.0/dcimcooling.js
lib/api/redfish-1.0/dcimpower.js
lib/api/redfish-1.0/managers.js
lib/api/redfish-1.0/networks.js
lib/api/redfish-1.0/systems.js
lib/services/redfish-api-service.js
lib/services/wsman-service.js
spec/lib/api/redfish-1.0/chassis-spec.js
spec/lib/api/redfish-1.0/managers-spec.js
spec/lib/api/redfish-1.0/system-spec.js
spec/lib/services/redfish-api-service-spec.js

Updating redfish to work with identifier in addition to mongo id
Correct Managers GET REST interfaces
Correct chassis GET REST interfaces
Correct systems GET REST interfaces
Adding put/post actions for redfish devices
Adding and fixing spec tests
************
Part of Changes in on-core, on-http, on-tasks, on-taskgraph
The combination of these changes is to fully implement redfish device discovery. This includes the fillowing items:
1) The implementation of unique device identifiers in place of the RackHD GUID identifers.
a) These ids provide the user the ability to know which node they are looking at. This is usefull for
aggregation.
b) All RackHD Redfish calls can use either the new id or the original RackHD GUID. The RackHD api still can
only use the GUID.
c) Currently this id is made …

Adding redfish node for chassis/system combo

---

data/views/catalogs.2.0.json
lib/services/catalogs-api-service.js
spec/lib/api/2.0/catalogs-spec.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/services/catalogs-api-service-spec.js

Expose timestamp for getAllCatalogs API. Otherwise user can't tell difference between catalogs with the same source and nodeId but created at different time.

 Expose timestamp for getAllCatalogs API 

---

lib/api/2.0/nodes.js
lib/api/2.0/tags.js
lib/services/nodes-api-service.js
lib/services/swagger-api-service.js
spec/lib/api/2.0/nodes-spec.js
spec/lib/services/nodes-api-service-spec.js

* FIX the issue that Cannot delete a tag from a node if tag contains spaces
(https://rackhd.atlassian.net/browse/RAC-6680)
* throw NotFoundError when tagName not found in nodes for API `/nodes/{identifier}/tags/{tagName}
`
depends on: https://github.com/RackHD/RackHD/pull/923
@RackHD/corecommitters @pengz1

Fix deleting tag issue from nodes in RAC-6680

---

lib/services/taskgraph-api-service.js

For method TaskgraphApiService.prototype.workflowsDeleteByInstanceId in lib/services/taskgraph-api-service.js, we should use "identifier" instead of "graphId".
It is defined in: https://github.com/RackHD/on-http/blob/master/lib/services/scheduler.proto#L84
@iceiilin @lanchongyizu

 Fix can't delete graph by instanceId issue
