RackHD/on-http

data/templates/setup_iso.py
Automate the process of deploying OS media (ISO) from a local/remote(http) to a local mirror and prepare the local mirror to be used as a target for network installation.
@tannoa2 @RackHD/corecommitters
=> VEY-219: Automate OS installation media setup

data/profiles/install-coreos.ipxe, data/templates/install-coreos.sh, data/templates/pxe-cloud-config.yml
- install not working in vagrant demo, so switching that PXE setup to only boot/run CoreOS while I sort out the specifics
=> enabling running CoreOS

data/templates/centos-ks, data/templates/esx-ks, data/templates/get_driveid.js
It is the fix of ODR-338, https://hwjiraprd01.corp.emc.com/browse/ODR-338
1. added driveId script to catalog to get wwid - drive mapping table.
2. Modified kickstart file to render installDisk info got from job 
Related PRs:
https://github.com/RackHD/on-tasks/pull/86
https://github.com/RackHD/on-taskgraph/pull/36
=> Added get_driveid script and modified kickstart file to assign drive dynamically

data/templates/get_driveid.js
Add script in on-http/data/templates folder for collecting drive IDs.
=> Add script to get drive IDs information

.bintray.json, .travis.yml
=> Deploy debian packages to bintray

.travis.yml
=> Generate API docs

app.js, index.js, lib/services/http-service.js, spec/helper.js, spec/lib/api/nodes-spec.js
* Also cleans up some rather confusing naming with `app.js`
Thanks to @benbp for helping me figure out the fix for this.
=> Fixes tests with node version 4

index.js, lib/api/files.js, lib/services/http-service.js, lib/services/nodes-api-service.js, lib/services/profiles-api-service.js, lib/services/sku-pack-service.js, lib/services/ws-resources.js, lib/services/ws-service.js
updating mapping to more constricted set of logs per
https://github.com/RackHD/RackHD/issues/34
**NOTE**: Requires https://github.com/RackHD/on-core/pull/48 to be
committed prior as it adds the synonym 'critical' to the existing 'crit'
level.
=> rationalizing logs

lib/api/nodes.js, lib/api/profiles.js
=> Correct params in apidocs

lib/api/profiles.js
=> Fix header param in profile PUT.

debianstatic/on-http/control, debianstatic/on-http/on-http.install
Move description and depends to single line
=> Install skupack.d directory

README.md
* Capitalized headers, fixed a typo, and improved text styles a little.
* Added instructions for using with `node-inspector`.
=> Updates README, adds node-inspector instructions.

data/templates/centos-ks
Added installation packages to install KVM for RHEL 7 and CentOS 7 in kickstart file.
=> Fixed KVM installation for RHEL 7 and CentOS 7

spec/helper.js
This change allows unit testing of swagger controllers using the unit test helper injector.
=> Setup DI for unit testing Swagger controllers

lib/services/http-service.js
@brianparry @jlongever @dalebremner @abildw @srinia6
=> prevent app.listen() from completing before swagger is ready

lib/api/1.1/config.js, lib/api/2.0/config.js, lib/services/config-api-service.js, spec/lib/api/2.0/config-spec.js, static/monorail-2.0.yaml, swagger_config/default.yaml
Add route and unit test for 2.0 config route
@brianparry @abildw @dalebremner @srinia6
=> Config route for 2.0 API

data/templates/redfish.1.0.0.chassis.1.0.0.json, data/templates/redfish.1.0.0.chassiscollection.json, data/templates/redfish.1.0.0.power.1.0.0.json, data/templates/redfish.1.0.0.thermal.1.0.0.json, lib/api/redfish-1.0/chassis.js, spec/lib/api/redfish-1.0/chassis-spec.js, static/redfish.yaml
- Add Chassis root and collections path
- Add Thermal reference object
- Add Power reference object
- Add unit-tests
@RackHD/corecommitters @zyoung51 @keedya @uppalk1 @tannoa2
=> Extend redfish API for Chassis

static/redfish.yaml
Add swagger model definitions for Redfish and update current routes to reflect proper error codes, summaries, and model schemas for the objects they return.
=> Update swagger definition

Dockerfile
Created a rackhd organization on docker hub.
=> Update dockerfile base name

install-swagger-ui.sh, lib/services/http-service.js, package.json
- Install the swagger-ui by running install-swagger-ui.sh
- Swagger UI will be at /swagger-ui
=> Add swagger-ui with login and combined swaggers

lib/api/1.1/northbound/nodes.js, lib/services/nodes-api-service.js, spec/lib/api/1.1/nodes-spec.js, spec/lib/services/nodes-api-service-spec.js
updated 1.1 controller and node service in preparation for Swagger 2.0 Node Controller.
Still passes all unit testing.
@geoff-reid @dalebremner @brianparry @srinia6 @RackHD/corecommitters
=> updated node service

data/templates/monorail-backup.sh, data/templates/monorail-restore.sh
@heckj @benbp 
Please do not merge this is blocked.
=> removed refs to onRack

data/templates/redfish.1.0.0.chassiscollection.json, lib/api/redfish-1.0/chassis.js, spec/lib/api/redfish-1.0/chassis-spec.js
Add URIs to GET chassis by serial number in addition to node id
=> Chassis by serial number

data/templates/redfish.1.0.0.power.1.0.0.json, data/templates/redfish.1.0.0.thermal.1.0.0.json, lib/api/redfish-1.0/chassis.js, spec/lib/api/redfish-1.0/chassis-spec.js
@RackHD/corecommitters @zyoung51 @tannoa2 @uppalk1 @keedya
=> Fix redfish power/thermal SDR parsing to match on-tasks PR# 99

.travis.yml
@RackHD/corecommitters @zyoung51
=> Bump swagger-codegen to v2.1.5

data/templates/redfish.1.0.0.computersystem.1.0.0.json, data/templates/redfish.1.0.0.rackhd.bootimage.json, data/templates/redfish.1.0.0.rackhd.reset.actions.json, lib/api/1.1/northbound/nodes.js, lib/api/redfish-1.0/systems.js, lib/services/nodes-api-service.js, lib/services/redfish-validator-service.js, spec/lib/api/redfish-1.0/system-spec.js, static/DSP8010_1.0.0/json-schema-oem/RackHD.BootImage.json, static/DSP8010_1.0.0/json-schema-oem/RackHD.ResetAction.json, static/redfish.yaml
- Add #Computer.Reset action to /Systems
- Add #RackHD.BootImage action to /Systems
- Refactor redfish validator to read schemaDirs from config
and added Oem schema to redfish v1
- Refactor systems to use node-service-api and makeOptions
=> [redfish] Add Reset and BootImage actions

lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
@RackHD/corecommitters @zyoung51
=> Check for undefined selData list

lib/fittings/swagger_render.js, lib/services/swagger-api-service.js, swagger_config/default.yaml
* Allows a rendering template to be specified in the Swagger definition file
=> Modified Swagger rendering fitting

lib/api/1.1/northbound/nodes.js, lib/api/2.0/config.js, lib/api/2.0/nodes.js, lib/api/serdes/nodes.js, lib/serializables/v1/node.js, lib/services/nodes-api-service.js, spec/lib/api/1.1/nodes-spec.js, spec/lib/api/2.0/nodes-spec.js, static/monorail-2.0.yaml
@RackHD/corecommitters @dalebremner @geoff-reid @srinia6
=> nodes 2.0 controller and unit tests

lib/services/common-api-presenter.js
=> Add scoped profile (skupack) support to the profile rendering path

lib/serializables/v1/obm.js, lib/serializables/v1/snmp.js, spec/lib/serializables/v1/node-spec.js, spec/lib/serializables/v1/obm-spec.js
@srinia6 @dalebremner @abildw @RackHD/corecommitters
=> Redact encrypted fields in OBM and SNMP serializer

static/monorail-2.0.yaml
This is the same as PR #149 which I accidentally closed.  
@RackHD/corecommitters @dalebremner @abildw @srinia6
=> Swagger ui work

lib/services/common-api-presenter.js, lib/services/sku-pack-service.js, spec/lib/api/1.1/templates-spec.js, spec/lib/services/sku-pack-service-spec.js
- Import skuConfig object from config.json into environment collection
- Add 'sku' and 'env' to profile/template rendering objects
=> [skupack] Add configuration/option import and rendering

lib/api/1.1/southbound/profiles.js, lib/services/profiles-api-service.js, spec/lib/api/1.1/profiles-spec.js, spec/lib/services/profiles-api-service-spec.js
Converge error handling and build single promise chain in /profiles api route.
@RackHD/corecommitters @zyoung51 @tannoa2 @uppalk1 @keedya
=> Fix Promise chain in profiles api

lib/api/2.0/nodes.js
@abildw @brianparry @srinia6 @dalebremner @RackHD/corecommitters
=> add lodash to nodes API file

lib/api/redfish-1.0/systems.js, lib/api/redfish-1.0/task-service.js, spec/lib/api/redfish-1.0/system-spec.js, spec/lib/api/redfish-1.0/task-service-spec.js, static/DSP8010_1.0.0/json-schema-oem/RackHD.BootImage.json, static/DSP8010_1.0.0/json-schema-oem/RackHD.ResetAction.json
- Fix ipv4 and ipv6 fields
- Add enum properties to osName
- Add required fields to json schema
- Update Task objects to align with workflow changes
=> RackHD Issue #116

lib/api/2.0/pollers.js, lib/services/pollers-api-service.js, spec/lib/api/2.0/pollers-spec.js, static/monorail-2.0.yaml
* Added content parameter to some /pollers routes
* Remove pollers pause and resume routes
=> Updates to v2 API for functional tests

data/templates/redfish.1.0.0.message.1.0.0.json, lib/api/redfish-1.0/chassis.js, lib/api/redfish-1.0/service-root.js, lib/api/redfish-1.0/session-service.js, lib/api/redfish-1.0/systems.js, lib/api/redfish-1.0/task-service.js, lib/services/redfish-validator-service.js, lib/services/schema-api-service.js, spec/lib/api/redfish-1.0/chassis-spec.js, spec/lib/api/redfish-1.0/service-root-spec.js, spec/lib/api/redfish-1.0/session-service-spec.js, spec/lib/api/redfish-1.0/system-spec.js, spec/lib/api/redfish-1.0/task-service-spec.js, spec/lib/services/redfish-validator-service-spec.js, spec/lib/services/schema-api-service-spec.js, static/DSP8010_1.0.0/DSP8011_1.0.0a.json
- Add redfish detailed error message
- Change 500 on invalid object to 404 with redfish detailed error message
- Change 202 Accepted to 201 Created when Tasks are created
- Add redfish message registry
- Refactor redfish validator to separate schema into a separate service
=> [redfish] Add detailed error message responses

lib/services/sku-pack-service.js
Resolves https://github.com/RackHD/RackHD/issues/128
=> Fix null check for node.sku in sku service setupScope

lib/api/1.1/northbound/skus.js, lib/services/sku-pack-service.js, spec/lib/api/1.1/skus-spec.js, spec/lib/services/sku-pack-service-spec.js
=> [skupack] Get pack information with sku information

data/templates/set_bmc_credentials.sh
=> Set bmc settings

lib/api/1.1/northbound/pollers.js, lib/serializables/v1/node.js, lib/services/nodes-api-service.js, lib/services/pollers-api-service.js, spec/lib/api/1.1/pollers-spec.js, spec/lib/api/2.0/pollers-spec.js
- Reference NodeType constants in POST /nodes
- Add redfish poller type for GET /poller/library
- Update unit-tests
@RackHD/corecommitters @zyoung51 @geoff-reid @uppalk1 @tannoa2 @keedya
=> Use node type constants

static/DSP8010_1.0.0/json-schema-oem/MessageRegistryFile.1.0.0.json, static/DSP8010_1.0.0/json-schema-oem/MessageRegistryFile.json, static/DSP8010_1.0.0/json-schema-oem/MessageRegistryFileCollection.json, static/redfish.yaml
- Change response definitions to use responses path to correct swagger
editor warnings
- Update definitions with output of new json-schema parser
- Add missing MessageRegistryFiles
=> [swagger] Update redfish.yaml

.gitignore, .travis.yml, README.md, build-package.bash, extra/Vagrantfile, extra/make-cicd.sh, extra/make-clean.sh, extra/make-deb.sh, extra/make-docs.sh, extra/make-npmdeps.sh, extra/make-npmtest.sh, extra/make-sysdeps.sh, extra/make-testcoveralls.sh
Ready for merge, pending testing.
This does the following:
1. Create extra directory containing make* scripts
2. Modify .travis.yml to utilize make* scripts
3. Modify build-package.bash to anticipate variables passed in.
4. A make-cicd.sh script that will emulate HWIMO-BUILD
5. Add Vagrantfile that will build package.
Travis Build using this method: https://travis-ci.org/ytjohn/on-http/builds/115897749
=> build refactor

data/templates/redfish.1.0.0.jsonschemafile.1.0.0.json, data/templates/redfish.1.0.0.jsonschemafilecollection.json, lib/api/redfish-1.0/schemas.js, lib/services/redfish-validator-service.js, lib/services/schema-api-service.js, spec/lib/api/redfish-1.0/schemas-spec.js, static/redfish.yaml
@jlongever @zyoung51 @amymullins @keedya @uppalk1
=> Add support for /schema /schema{identifier} in the redfish API

data/templates/redfish.1.0.0.messageregistryfile.1.0.0.json, data/templates/redfish.1.0.0.messageregistryfilecollection.1.0.0.json, data/templates/redfish.1.0.0.serviceroot.1.0.0.json, lib/api/redfish-1.0/registry.js, lib/services/redfish-validator-service.js, spec/lib/api/redfish-1.0/registry-spec.js, static/redfish.yaml
@jlongever @zyoung51 @amymullins @tannoa2 @keedya
=> Redfish api registries

lib/services/nodes-api-service.js
@RackHD/corecommitters @uppalk1 @tannoa2 @zyoung51 @keedya @geoff-reid
=> Distinguish error cases in delActiveWorkflowById()

lib/api/1.1/northbound/config.js, lib/api/2.0/config.js, lib/services/config-api-service.js, static/monorail-2.0.yaml
* updating config route to use swagger controller 
@dalebremner @geoff-reid @brianparry @srinia6 @RackHD/corecommitters
=> config route refactor

lib/api/2.0/pollers.js, lib/services/pollers-api-service.js
Resolves https://github.com/RackHD/RackHD/issues/150
@brianparry @dalebremner @abildw @geoff-reid @RackHD/corecommitters
=>  2.0 API pollers tests occasionally fail #150 

lib/fittings/rackhd_validator.js, lib/services/swagger-api-service.js, spec/lib/services/swagger-api-service-spec.js, static/monorail-2.0.yaml, static/schemas/2.0/Node.2.0.json, swagger_config/default.yaml
@RackHD/corecommitters @zyoung51 @srinia6 @geoff-reid @abildw
=> API 2.0 swagger validator

data/templates/redfish.1.0.0.logentry.1.0.0.json, data/templates/redfish.1.0.0.logentrycollection.json, lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
- Translate sensor type and event type from ipmitool defintions to
redfish compliant definitions
- Fixup sensorNumber and OriginOfCondition values
Resolves https://github.com/RackHD/RackHD/issues/108
=> Translate ipmitool sel output to redfish compliant output

lib/api/1.1/northbound/skus.js, lib/services/sku-pack-service.js
Resolves https://github.com/RackHD/on-http/issues/220
@RackHD/corecommitters @uppalk1 @keedya @tannoa2 @rolandpoulter
=> Handle invalid gzip files in pipe chain

data/views/collection.2.0.json, data/views/node.2.0.json, data/views/obm.2.0.json, data/views/sample.json, lib/fittings/swagger_render.js, lib/services/swagger-api-service.js, spec/lib/api/2.0/nodes-spec.js, spec/lib/api/2.0/obms-spec.js, spec/lib/services/swagger-api-service-spec.js, static/monorail-2.0.yaml, swagger_config/default.yaml
Add support for rendering views to 2.0 API.  Also add views for /nodes and /obms
=> API 2.0  view rendering

lib/api/1.1/northbound/skus.js, lib/services/sku-pack-service.js, package.json, spec/lib/api/1.1/skus-spec.js, spec/lib/api/2.0/skus-spec.js, static/monorail-2.0.yaml
- Add handling for multipart/form-data to skupack POST/PUT routes
Resolves https://github.com/RackHD/on-http/issues/223 @RackHD/corecommitters @uppalk1 @tannoa2 @keedya
=> Handle multipart/form-data content type for skupack uploads

data/templates/redfish.1.0.0.logservice.1.0.0.json, data/templates/redfish.1.0.0.task.1.0.0.json, data/templates/redfish.1.0.0.taskcollection.json
@RackHD/corecommitters @uppalk1 @tannoa2 @keedya
=> [redfish] Omit end timestamp when it is empty

data/profiles/install-coreos.ipxe
resolving my self-inflicted editing stupidity - profile wouldn't render with the updates since I didn't balanced the tags correctly, even though it's "commented out" in the iPXE script.
Yes, @heckj is a big dummy.
=> resolve self-inflicted stupidity in editing

lib/api/redfish-1.0/registry.js, spec/lib/api/redfish-1.0/registry-spec.js
@RackHD/corecommitters @uppalk1 @tannoa2 @keedya
=> [redfish] Should 404 on invalid registry

lib/api/2.0/nodes.js, lib/api/2.0/workflows.js, static/monorail-2.0.yaml
* Change POST nodes/{identifier}/workflows to use swagger query object.
* Add query parameter to POST /workflows to accept workflow.
=> Fix for Issue #171

lib/api/redfish-1.0/schemas.js, lib/services/redfish-validator-service.js, lib/services/schema-api-service.js, spec/lib/api/redfish-1.0/schemas-spec.js
@RackHD/corecommitters @uppalk1 @tannoa2 @keedya
=> [redfish] Should 404 invalid schema uri

lib/api/2.0/skus.js, lib/services/sku-pack-service.js, spec/lib/api/2.0/skus-spec.js, spec/lib/services/sku-pack-service-spec.js, static/monorail-2.0.yaml
- Modify POST /skus to 409 on name conflict
- Create PUT /skus to upsert a sku definition
- Modify POST /skus/pack to 409 on name conflict
@RackHD/corecommitters @uppalk1 @tannoa2 @keedya @brianparry 
Resolves https://github.com/RackHD/RackHD/issues/113
=> Add skus PUT to upsert sku definitions

lib/api/1.1/northbound/nodes.js, lib/api/2.0/nodes.js, lib/api/serdes/nodes.js, lib/serializables/v1/node.js, lib/serializables/v1/ssh.js, lib/services/nodes-api-service.js, lib/services/rest-api-service.js, spec/lib/api/1.1/nodes-spec.js, spec/lib/api/2.0/nodes-spec.js, spec/lib/serializables/v1/ssh-spec.js, spec/lib/services/rest-api-service-spec.js, static/monorail-2.0.yaml, static/schemas/2.0/Node.2.0.json
Supports https://github.com/RackHD/on-core/pull/116
@RackHD/corecommitters @VulpesArtificem @heckj 
EDIT: whoops, forgot to add https://github.com/RackHD/on-core/pull/116 is required first.
=> Add node SSH settings serializable and routes

lib/services/tags-api-service.js
Resolves https://github.com/RackHD/RackHD/issues/200
=> Change from decodeURI to decodeURIComponent

spec/lib/api/redfish-1.0/event-service-spec.js, static/redfish.yaml
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @geoff-reid @keedya
=> [redfish] Updates test event path parameter

lib/services/http-service.js, spec/lib/api/login/login-spec.js, spec/lib/services/auth-service-spec.js
Fix issue #195 by adding return to promise.
https://github.com/RackHD/RackHD/issues/195
=> Fix RackHD issue #195

lib/api/2.0/schemas2.js, lib/services/swagger-api-service.js, spec/lib/api/2.0/schemas-spec.js, static/monorail-2.0.yaml
@RackHD/corecommitters @zyoung51 @srinia6 @abildw @geoff-reid
=> API 2.0 Schemas Routes

data/profiles/taskrunner.py, data/templates/arista-catalog-config.py, data/templates/arista-catalog-snmp-settings.py, data/templates/arista-catalog-version.py, data/templates/arista-deploy-startup-config.py, data/templates/arista-startup-config
This PR contains startup script for Arista as well as catalog scripts.  The Arista CLI does not support return of JSON format for most of the commands so needed to do parsing of the data.
@RackHD/corecommitters @benbp @heckj @VulpesArtificem @johren
=> Adding arista catalog, config scripts

lib/api/redfish-1.0/event-service.js, spec/lib/api/redfish-1.0/event-service-spec.js
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @geoff-reid @keedya 
Dependent PR https://github.com/RackHD/on-tasks/pull/180
=> [redfish] Add FabricService alert handler to EventService

data/views/tasks.2.0.json, lib/api/2.0/tasks.js, lib/services/task-api-service.js, spec/lib/api/2.0/tasks-spec.js, static/monorail-2.0.yaml
@benbp @abildw @brianparry @dalebremner @geoff-reid @RackHD/corecommitters
=> Add tasks schema

lib/api/1.1/northbound/files.js, lib/api/1.1/southbound/files.js, spec/lib/api/1.1/files-spec.js
To solve issue #215. 
PR https://github.com/RackHD/on-http/pull/230 has merged to master, and it's also needed for 1.2 release branch
- Add file latest and file md5 latest router to south file router
- Add unit test
=> Add file latest and file md5 latest to south API router

lib/api/redfish-1.0/task-service.js, lib/services/workflow-api-service.js
Requires: https://github.com/RackHD/on-core/pull/120
For ODR-593 and https://www.pivotaltracker.com/n/projects/1492888/stories/115448753
=> Set initial graph state to running.

data/templates/centos-ks, data/templates/install-ubuntu/post-install-ubuntu.sh
change uid to optional  for centos and Ubuntu;
and SUSE has supported uid optional, 
EXS don't support uid input.
@yyscamper @iceiilin @panpan0000
=> change uid to optional

lib/api/2.0/skus.js, spec/lib/api/2.0/skus-spec.js, spec/lib/services/sku-pack-service-spec.js, static/monorail-2.0.yaml
Modified few tests to remove dependencies
=> Skus Unit Test update

data/templates/centos-ks
temporarily only support CentOS, CentOS is a starting point, other Linux OS will be added. 
more description, please see docs PR: https://github.com/RackHD/docs/pull/278
related PR: https://github.com/RackHD/on-tasks/pull/213
also address ODR-654 https://hwjiraprd01.corp.emc.com/browse/ODR-654
=> Support partitioning for CentOS installation

data/views/profiles.2.0.json, lib/api/2.0/profiles.js, lib/services/profiles-api-service.js, lib/services/swagger-api-service.js, spec/lib/api/2.0/profiles-spec.js, spec/lib/services/http-service-spec.js, spec/lib/services/profiles-api-service-spec.js, spec/lib/services/ws-service-spec.js, static/monorail-2.0.yaml
This PR has contributions from @srinia6 @geoff-reid @BillyAbildgaard @dalebremner and @brianparry .
Requires https://github.com/RackHD/on-http/pull/296 PR 
@RackHD/corecommitters @zyoung51 @jlongever @amymullins
=> 2.0 API profiles routes

data/templates/arista-catalog-ip.py
@RackHD/corecommitters @benbp 
Adding in new catalog script for Arista to obtain IP address used during DHCP process.
=> Adding Arista specific catalog script to get IP address

lib/api/redfish-1.0/chassis.js, spec/lib/api/redfish-1.0/chassis-spec.js
@RackHD/corecommitters @zyoung51 @tannoa2 @uppalk1 @keedya 
Fixes mapping bug in Redfish /Chassis/:identifier resource.
=> Map chassis status UID values to valid Redfish values

lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya 
Same as #304 but for Systems.
=> Map UID values to Redfish values for System resources

lib/services/upnp-service.js
- addMembership for the proper router to the SSDP server
- advertise the 2.0 southbound endpoint
=> Add southbound SSDP notifications

lib/api/2.0/profiles.js, lib/services/profiles-api-service.js
=> Fixed southbound profiles route

data/profiles/winpe.ipxe, data/templates/startup.ps1, data/templates/unattend_server2012.xml, data/templates/winpe-kickstart.ps1, lib/api/2.0/templates.js, lib/fittings/json_error_handler.js
The data/templates/startup.ps1 File will be added to the winpe image. Once Winpe boots up, the script will first discover the RackHD advertised IP.
Then it cruls a rendered  unattended.xml file that has the OS settings from the user.
Lastly it curls the winpe-kickstart.ps1 script and runs it. The winpe-kickstart.ps1 script mounts the Windows server ISO image and kicks off the installation process.
=> Windows Server 2012

lib/api/2.0/nodes.js, lib/api/2.0/workflows.js, lib/services/nodes-api-service.js, lib/services/workflow-api-service.js, spec/lib/api/2.0/nodes-spec.js, spec/lib/api/2.0/workflows-spec.js, static/monorail-2.0.yaml
refactored nodes/workflows to be consistent with the /workflows route
@RackHD/corecommitters @dalebremner @srinia6 @brianparry
=> refactor nodes/workflows

data/templates/get_driveid.js, spec/data/templates/get_driveid-spec.js
It is found JBOD have virtual disk attribute, this update is to remove this attribute for JBOD disks.
=> Remove virtual disk feature for JBOD disk

.travis.yml, debianstatic/on-http/control
based on PR https://github.com/RackHD/docs/pull/286,
@RackHD/corecommitters @benbp @jlongever @heckj
=> deb package creation and dependency based on node 4

lib/services/nodes-api-service.js, spec/lib/services/nodes-api-service-spec.js
Send amqp alert on node delete.
=> Send amqp alert on node delete

lib/api/2.0/obms.js, lib/fittings/rackhd_validator.js, lib/services/nodes-api-service.js, lib/services/swagger-api-service.js, spec/lib/api/2.0/obms-spec.js, static/monorail-2.0.yaml, static/schemas/obms/amt-obm-service.json, static/schemas/obms/apc-obm-service.json, static/schemas/obms/ipmi-obm-service.json, static/schemas/obms/noop-obm-service.json, static/schemas/obms/panduit-obm-service.json, static/schemas/obms/raritan-obm-service.json, static/schemas/obms/servertech-obm-service.json, static/schemas/obms/vbox-obm-service.json, static/schemas/obms/vmrun-obm-service.json
@RackHD/corecommitters @jlongever @zyoung51 @srinia6 @BillyAbildgaard 
Depends on:
RackHD/on-core#164
RackHD/on-tasks#243
=> API 2.0 OBM Routes

lib/services/sku-pack-service.js
Resolves https://github.com/RackHD/RackHD/issues/296
=> Reset skupack fields to null during delete

data/views/error.2.0.json, lib/fittings/error_handler.js, lib/services/swagger-api-service.js, spec/lib/api/2.0/views-spec.js, spec/lib/api/2.0/workflowTasks-spec.js, spec/lib/api/2.0/workflows-spec.js, spec/lib/fittings/json_error_handler_spec.js, spec/lib/services/swagger-api-service-spec.js, swagger_config/default.yaml
@RackHD/corecommitters @BillyAbildgaard @keedya @zyoung51
=> 2.0 API error handling modifications

data/views/tasks.2.0.json
-Required by shell boot
@RackHD/corecommitters @brianparry @BillyAbildgaard @dalebremner
=> Add exit property to task view

lib/api/redfish-1.0/systems.js
=> Change Graph.InstallEsx to Graph.InstallESXi

data/profiles/taskrunner.py, data/templates/brocade-catalog-version.py, data/templates/brocade-vdx-deploy-config.py, lib/services/profiles-api-service.js
Added support for brocade switch discovery. Following changes are made
- taskrunner.py:
Modified the script to replace the functions which is not compatible with python 3.
- data/templates/brocade-catalog-version.py:
script used to catalog as part of auto discovery process
- data/templates/brocade-vdx-deploy-config.py:
script used to deploy a config file to running
=> Brocade VDX switch integration as part of switch discovery

data/templates/redfish.1.0.0.computersystem.1.0.0.json
=> Fix Dell C6320 'TotalSystemMemoryGiB' is 0.25

data/views/node.2.0.json, spec/lib/api/2.0/nodes-spec.js
Add links, and new fields for easy navigation. @dalebremner @keedya @BillyAbildgaard @RackHD/corecommitters
=> Nodes view clean-up

static/monorail-2.0.yaml, static/schemas/2.0/skus.2.0.json
adding schema for /skus POST and PUT.
@RackHD/corecommitters @dalebremner @keedya @srinia6
=> skus schema

static/monorail-2.0.yaml
@RackHD/corecommitters @srinia6 @keedya @BillyAbildgaard
=> Swagger description updates

lib/api/2.0/nodes.js, lib/services/nodes-api-service.js, static/monorail-2.0.yaml
@RackHD/corecommitters @hohene @amymullins @srinia6 @BillyAbildgaard
=> Add query by type back to API GET /nodes

data/templates/bootstrap.js
This PR addresses a case were, if we are performing tasks such as flashing BIOS, we would  currently stop attempting to report a nodes success to a server (in the event that the server is down for some reason), after a set amount of retries. In such an event, we could have a disconnection between current and expected state on that node. This implements a fix that will have the node attempt to report its success indefinitely, until the server responds.
=> Implement BootStrap Status Infinite Retries 

lib/api/1.1/northbound/skus.js, lib/services/sku-pack-service.js, spec/lib/services/sku-pack-service-spec.js
- Update 1.1 and 2.0 `DELETE /skus/:id` API.
@RackHD/corecommitters @uppalk1 @tannoa2 @keedya @zyoung51
=> Remove skupack on DELETE /skus/:id

data/views/workflowTasks.2.0.json, spec/lib/api/2.0/workflowTasks-spec.js, static/monorail-2.0.yaml
Add workflowTasks view and fix unit-test. @RackHD/corecommitters @brianparry @keedya @dalebremner @BillyAbildgaard
=> workflowTasks view and unit-test fix

lib/api/2.0/nodes.js, static/monorail-2.0.yaml
- This option already exist in api 1.1
@brianparry @zyoung51 @RackHD/corecommitters @dalebremner @amymullins @srinia6
=> Support in 2.0 querying by value of any key in the array of nodes object

data/templates/redfish.1.0.0.chassis.1.0.0.json, lib/fittings/swagger_locals.js, lib/services/redfish-validator-service.js, spec/lib/api/redfish-1.0/chassis-spec.js, static/redfish.yaml
=> [redfish] Add northbound sku assignment to /Chassis routes

lib/services/http-service.js, spec/lib/api/1.1/notification-spec.js, spec/lib/api/2.0/notification-spec.js, spec/lib/services/notification-api-service-spec.js, static/monorail-2.0-sb.yaml
@amymullins @heckj @RackHD/corecommitters @dalebremner @srinia6 @brianparry
=> Set routes current and common to 2.0 by default

data/views/sku-2.0.json, static/monorail-2.0.yaml
@RackHD/corecommitters @brianparry @dalebremner @srinia6 @BillyAbildgaard
=> Add sku view

static/monorail.yml
partial doc fix for for https://github.com/RackHD/RackHD/issues/363
=> partial doc

data/templates/redfish.1.0.0.chassis.1.0.0.json, lib/api/redfish-1.0/chassis.js, spec/lib/api/redfish-1.0/chassis-spec.js
ODR-795: no blade nodes are contained in the chassis list
- Add blade nodes to chassis list
- Add Contains and ContainedBy member lists
ODR-796: duplicate entries for each enclosure using nodeid and
chassis serialno
- Remove listing by serial number
ODR-793: ChassisType should reflect Enclosure, Rackmount, or
Blade as opposed to 'Other'
=> [redfish] Resolve chassis related ODR

data/views/error.2.0.json, lib/fittings/error_handler.js, lib/services/http-service.js
* Add UUID to res.locals and add to error template.
* Log UUID from httpEventMiddleware.
@benbp @yyscamper: As discussed in Slack
=> Add UUID to HTTP responses

data/views/users.2.0.json, static/monorail-2.0.yaml
@RackHD/corecommitters @BillyAbildgaard @srinia6 @keedya
=> Added view for users route

static/monorail-2.0.yaml, static/schemas/2.0/user.2.0.json
@RackHD/corecommitters @srinia6 @BillyAbildgaard @keedya
=> Added schema to users route

data/profiles/taskrunner.py, data/templates/cisco-deploy-config-and-images.py
* Add logging
* Correct imports
* Use urllib2 instead of requests
=> on-2917 - Get POAP workflows operation in RackHD 2.0+ for the Cisco switches

data/views/tags.2.0.json, spec/lib/api/2.0/tags-spec.js, static/monorail-2.0.yaml, static/schemas/2.0/skus.2.0.json, static/schemas/2.0/tags.2.0.json
@RackHD/corecommitters @dalebremner @keedya @geoff-reid @srinia6
=> 2.0 view and schema

data/views/workflowGraphs.2.0.json, data/views/workflowTasks.2.0.json, lib/services/swagger-api-service.js, spec/lib/api/2.0/workflowGraphs-spec.js, static/monorail-2.0.yaml
Add view to workflowGraphs and fix unit-test.
@brianparry @BillyAbildgaard @keedya @dalebremner @RackHD/corecommitters
=> Add workflowGraphs view and fix unit-test

spec/lib/api/2.0/lookups-spec.js, spec/lib/api/2.0/nodes-spec.js, spec/lib/api/2.0/obms-spec.js, static/monorail-2.0.yaml
@RackHD/corecommitters @brianparry @srinia6 @BillyAbildgaard @dalebremner @geoff-reid
=> Add missing definitions in monorail 2.0 yaml file

data/templates/esx-ks
@RackHD/corecommitters @brianparry @srinia6 @dalebremner @geoff-reid @BillyAbildgaard
=> Fix Bootstrap payload for esxi fails when IPv4 is set as static

lib/api/2.0/nodes.js, lib/api/2.0/pollers.js, lib/api/2.0/workflows.js, lib/fittings/error_handler.js, lib/services/http-service.js, lib/services/nodes-api-service.js, lib/services/pollers-api-service.js, lib/services/swagger-api-service.js, lib/services/workflow-api-service.js, package.json, spec/lib/api/2.0/nodes-spec.js, spec/lib/api/2.0/pollers-spec.js, spec/lib/api/2.0/views-spec.js, spec/lib/api/2.0/workflowTasks-spec.js, spec/lib/api/2.0/workflows-spec.js, spec/lib/services/pollers-api-service-spec.js, spec/lib/services/swagger-api-service-spec.js, static/monorail-2.0.yaml
This PR adds support for pagination using $skip and $top query parameters. 
@RackHD/corecommitters @keedya @geoff-reid @dalebremner @BillyAbildgaard @srinia6 @rolandpoulter
=> Pagination support for nodes, workflows, and pollers routes

lib/services/http-service.js
* Chain swagger registration promises to avoid race condition.
Resolves https://github.com/RackHD/on-http/issues/444
=> Fix issue with Swagger UI showing only southbound routes.

data/profiles/taskrunner.py
@RackHD/corecommitters @johren
=> Remove vendor information and replace with library used.

lib/api/2.0/nodes.js, lib/services/nodes-api-service.js, spec/lib/api/2.0/nodes-spec.js, spec/lib/services/nodes-api-service-spec.js, static/monorail-2.0.yaml, static/schemas/obms/amt-obm-service.json, static/schemas/obms/apc-obm-service.json, static/schemas/obms/ipmi-obm-service.json, static/schemas/obms/noop-obm-service.json, static/schemas/obms/panduit-obm-service.json, static/schemas/obms/raritan-obm-service.json, static/schemas/obms/redfish-obm-service.json, static/schemas/obms/servertech-obm-service.json, static/schemas/obms/vbox-obm-service.json, static/schemas/obms/vmrun-obm-service.json
This PR requires https://github.com/RackHD/on-core/pull/202
@brianparry @RackHD/corecommitters @BillyAbildgaard @srinia6 @dalebremner @keedya
=> Add GET and PUT for nodes/id/obm in the 2.0 API

lib/api/2.0/templates.js, static/monorail-2.0.yaml
* Add separate controller for HEAD /templates to keep operationId unique.
=> Fix Swagger editor error

data/profiles/bootdisk-firstdisk.ipxe, data/profiles/diskboot.ipxe, data/profiles/end-ipxe.ipxe, lib/api/1.1/northbound/profiles.js
PR resolving rackhd/rackhd#390
- adding ipxe that specifically forces first disk boot
- renaming existing 'diskboot' to be more specific about fall through to BIOS boot order
=> Forcebootdisk

lib/api/2.0/tags.js, lib/services/tags-api-service.js, spec/lib/api/1.1/tags-spec.js
Requires https://github.com/RackHD/on-tasks/pull/320 and https://github.com/RackHD/on-taskgraph/pull/162 (interdependent).
@RackHD/corecommitters @heckj @pscharla
=> Run a single workflow with an array of nodeIds for tag generation

lib/api/2.0/users.js, lib/api/redfish-1.0/account-service.js, spec/lib/api/2.0/users-spec.js, spec/lib/api/redfish-1.0/account-service-spec.js
object
Depends on https://github.com/RackHD/RackHD/pull/406
=> Return 400 rather than ignoring unused parametersi in the request

data/views/users.2.0.json, lib/api/2.0/roles2.0.js, lib/services/account-api-service.js, spec/lib/api/2.0/roles2.0-spec.js, spec/lib/services/account-api-service-spec.js, static/monorail-2.0.yaml
depends on https://github.com/RackHD/on-core/pull/208
- Update users view and remove privilege property
@brianparry @zyoung51 @amymullins @srinia6 @dalebremner @BillyAbildgaard @geoff-reid
=> Add roles route to 2.0 apis

data/templates/autounattend_windows_2012_r2_SMC_6028U-TR4+.xml, data/templates/autounattend_windows_2012_r2_unknown.xml, data/templates/autounattend_windows_2012_r2_vmware.xml, data/templates/centos-ks, data/templates/centos.rackhdcallback, data/templates/esx-ks, data/templates/esx.rackhdcallback, data/templates/install-coreos.sh, data/templates/install-photon/photon-os.rackhdcallback, data/templates/install-ubuntu/ubuntu-preseed, data/templates/post-windows-install.ps1, data/templates/suse-autoinst.xml, data/templates/winpe-kickstart.ps1
* replace completionUri with notification in OS kickstart files
* additional works include:
- esx: move the install-os completion into esx-ks %post, and remove postLookup
- windows: move the install-os completion into winpe-kickstart.ps1
=> Replace completionUri with notification

debianstatic/on-http/on-http.init
- enable start/stop/restart and pid monitoring
- put logs in /var/log/rackhd
https://github.com/RackHD/on-http/issues/416
=> Better init script

data/views/poller.2.0.json
@RackHD/corecommitters @srinia6 @keedya
=> fix typo in poller view

static/apidoc/footer.md, static/apidoc/header.md
- also updated copyright since I was in the files
=> fixing broken link in taskdoc annotations

data/templates/esx-ks
@brianparry @zyoung51 @RackHD/corecommitters @amymullins @jlongever @tannoa2 @uppalk1 
@yyscamper @lanchongyizu 
resolves https://github.com/RackHD/RackHD/issues/420
=> Add post Lookup functionality back to esxi ks

data/views/redfish-1.0/redfish.1.0.0.manageraccount.1.0.0.json, data/views/redfish-1.0/redfish.1.0.0.rackhd.reset.actions.json
Dependent on: https://github.com/RackHD/RackHD/pull/421
=> [redfish] Remove unused/unsupported fields for ODR-861 and ODR-879

Dockerfile
Replaces `apk` commands with `apt-get`
=> Updates Dockerfile to use debian wheezy

static/redfish.yaml
Add required specifier for /AccountService/Account post action
=> Resolve ODR-923

data/templates/cloud-config.yaml, lib/services/common-api-presenter.js, lib/services/http-service.js, lib/services/swagger-api-service.js, spec/lib/services/common-api-presenter-spec.js, spec/lib/services/swagger-api-service-spec.js
* seperate static file of bootstrap and os repos from api.server into file.server
@RackHD/corecommitters @iceiilin @cgx027 @panpan0000 @benbp 
https://github.com/RackHD/on-tasks/pull/347
https://github.com/RackHD/on-taskgraph/pull/173
=> seperate static file of bootstrap and os repos from api.server into file.server

data/templates/esx-ks
Disable firewall during post install script to allow access
to the notification url.
=> Fix ESXi 5.5 install

lib/api/redfish-1.0/managers.js, lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/managers-spec.js, spec/lib/api/redfish-1.0/system-spec.js
- Update Redfish to use new OBM models
- Resolve issues where /Managers was returning 200 with an error
payload when it should 404
=> [redfish] Resolve ODR-920 and ODR-927

extra/swagger-doc.js, package.json, static/monorail-2.0.yaml
* Cleanup errors in API 2.0 swagger definition
* Add script to generate documentation in PDF form
=> Swagger documentation generator

lib/services/nodes-api-service.js, spec/lib/services/nodes-api-service-spec.js
fix for https://hwjiraprd01.corp.emc.com/browse/ODR-882 
and https://hwjiraprd01.corp.emc.com/browse/ODR-885
=> Fixed bug: a node can be containedBy two rack

README.md
=> Add bintray link to readme

.gitignore
@RackHD/corecommitters @iceiilin @pengz1 @cgx027 @zyoung51
=> update gitignore: ignore taskdoc & skupack.d folder

data/templates/install-ubuntu/ubuntu-preseed, data/templates/install-ubuntu/ubuntu.rackhdcallback
Dependency on PR https://github.com/RackHD/on-tasks/pull/366 https://github.com/RackHD/on-taskgraph/pull/178
=> Add callback script to ubuntu installation workflow

data/templates/brocade-catalog-version.py
Change the catalog script according to sku definition change done in on-skupack PR#28
=> Modify  brocade catalog script

extra/swagger-doc.js
@RackHD/corecommitters @srinia6 @BillyAbildgaard
=> Added Redfish pdf file generation

data/templates/install-ubuntu/ubuntu-interfaces, data/templates/install-ubuntu/ubuntu-preseed
- fix support for vlan setup
- enable root ssh
=> Support minimal maximal payload for ubuntu

debianstatic/on-http/on-http.init
1. This PR removed the "--force".
Because ubuntu 16.04 doesn't support the option.
2. This PR added time interval after starting and stopping service. 
Because sometimes the service won't start but will later when running the command "service start" 
@yyscamper @anhou @panpan0000
=> enhance the debian init script to support ubuntu 16.04

data/templates/centos-ks
@keedya @tannoa2 @uppalk1 @RackHD/corecommitters
=> Fixed centos-ks for 6.5 max payload install

data/templates/unattend_server2012.xml, debianstatic/on-http/on-http.init, static/DSP8010_1.0.0/json-schema-oem/RackHD.BootImage.json, static/monorail-2.0.yaml
disable firewall to be able to test link after the static IP is assigned to the node as part of max payload
=> Windows os regression script enhancement

data/templates/secure_erase.py, lib/services/notification-api-service.js, lib/services/workflow-api-service.js, spec/lib/services/notification-api-service-spec.js, spec/lib/services/workflow-api-service-spec.js
Related PR: 
RackHD/on-tasks#364, 
RackHD/on-core#221, 
https://github.com/RackHD/on-taskgraph/pull/177
This PR is to implement secure erase progress feature.
Secure erase task progress is implemented in secure_erase.py.
Notification API with task id is used to deliver progress info from node to RackHD.
=> Implement se progress feature

data/templates/suse-autoinst.xml
-To make the static Ip work
-Added a post notication callback
=> Update the suse ks-script:

data/templates/pxe-cloud-config.yml
updating coreOS yaml to be able to template options passed in via the body.
@srinia6 @dalebremner @keedya @tannoa2 @geoff-reid @uppalk1
=> adding more options support in CoreOS yaml

app.js, lib/api/2.0/files.js, lib/services/static-files-api-service.js, package.json, spec/lib/services/static-files-api-service-spec.js, static/monorail-2.0.yaml
Re-opening PR
Requires https://github.com/RackHD/on-core/pull/183
which adds constants to to constants.js
Introduces api call, '/files/static/list', which returns a list of static files to the user. Example output as follows...
{
"uri": "/common/vmlinuz-3.16.0-25-generic"
},
{
"sku": "Cisco Nexus 3000 Switch - 54 port",
"uri": "static/common/aTestFile.we"
},
=> List static files

lib/services/profiles-api-service.js, spec/lib/services/profiles-api-service-spec.js
- optional and configurable
@RackHD/corecommitters @geoff-reid @tannoa2 @uppalk1
=> Add set obm settings on dynamic discovery

lib/services/profiles-api-service.js, spec/lib/services/profiles-api-service-spec.js
@anhou @yyscamper @RackHD/corecommitters
=> Rename option obmOption to be more significant autoCreateObm

data/templates/ignition.json, data/templates/install-coreos.sh
Add support to CoreOS GRUB configuration to support bare-metal Ignition templating support.
=> Inject GRUB customizations to support CoreOS Ignition

debianstatic/on-http/changelog, package.json
Prepare to Release
* change debian/package version and contacts.
@panpan0000 @PengTian0
=> [skip ci]modify debian info for release

extra/swagger-doc.js, static/monorail-2.0.yaml, static/redfish.yaml
=> Change title names for doc generation

install-task-doc.sh, static/taskdoc/api_project.js
Fix following task annotation problems:
(1) Fix the link for developer guide.
(2) Change copyright.
(3) Change file format (run dos2unix)
@anhou @iceiilin @pengz1 @brianparry @WangWinson
=> Fix task annotation

lib/serializables/v1/snmp.js, spec/lib/serializables/v1/node-spec.js, spec/lib/serializables/v1/snmp-spec.js, spec/lib/serializables/v1/ssh-spec.js
fixing unit test failures 
@RackHD/veyron
=> fixing unit tests

data/templates/get_driveid.js
With this line changed, we can get drives that have /dev/sdaa and beyond.
=> 'Allowing for systems with more than 26 drives'

data/views/hook.2.0.json, lib/api/2.0/hooks.js, lib/services/hooks-api-service.js, spec/lib/api/2.0/hooks-spec.js, spec/lib/services/hooks-api-service-spec.js, static/monorail-2.0.yaml, static/schemas/2.0/hooks.2.0.json
Hook is required in RI-46: https://rackhd.atlassian.net/browse/RI-46
This PR is to implement RackHD hook API design for user. User can use those APIs to review, update or delete hooks managed by RackHD.
POST/GET/DELETE/PATCH API methods are implemented for hooks.
=> Hook API design

data/templates/get_driveid.js
This PR is to fix git hub issue 571: get_driveid.js. is not creating the virtualDisk attribute.
Issue 571 is caused by  "vd" attribute missing for JBOD disks, this PR will default set "vd" to an empty string for all disks.
=> Fix GitHub issue 571

lib/services/notification-api-service.js, lib/services/workflow-api-service.js, spec/lib/services/notification-api-service-spec.js, spec/lib/services/workflow-api-service-spec.js
Implement workflow level progress indicator after task level progress.
https://rackhd.atlassian.net/browse/RAC-3923
@RackHD/corecommitters @pengz1 @iceiilin
=> workflow level progress

lib/services/notification-api-service.js, lib/services/workflow-api-service.js, spec/lib/api/2.0/nodes-spec.js, spec/lib/services/notification-api-service-spec.js, spec/lib/services/taskgraph-api-service-spec.js, spec/lib/services/workflow-api-service-spec.js, spec/mock-consul-server.js, spec/mock-grpc.js
fixing hound errors found in the PR against master https://github.com/RackHD/on-http/pull/588
Jenkins dependencies are set up in that PR
@RackHD/veyron 
jenkins: depends on https://github.com/RackHD/on-taskgraph/pull/217
=> fixing hound errors

data/templates/set_bmc_credentials.sh
bug fix https://github.com/RackHD/RackHD/issues/593
1, check if the exists count reach the MAX user count
2, Auto figure out the empty userID for adding new user
eg:
exists userID 1,2,7.
we will add the new user as id=3
=> bug fix #593

data/profiles/windows.ipxe, data/templates/post-windows-install.ps1, data/templates/winpe-kickstart.ps1
Inject progress milestones into Windows Server 2012, which is part of https://rackhd.atlassian.net/browse/RAC-3920
jenkins: depends on https://github.com/RackHD/on-tasks/pull/409
@RackHD/corecommitters @pengz1
=> progress milestones for Windows Server 2012

data/templates/secure_erase.py, lib/api/2.0/notification.js, lib/services/notification-api-service.js, lib/services/workflow-api-service.js, spec/lib/api/2.0/notification-spec.js, spec/lib/services/notification-api-service-spec.js, spec/lib/services/workflow-api-service-spec.js
Refactor workflow progress implementation with progress service design.
1) publish graph.started event for AMQP
2) move postProgressNotification into Services.GraphProgress
This PR is related with https://rackhd.atlassian.net/browse/RAC-4390
Depends on https://github.com/RackHD/on-core/pull/261 https://github.com/RackHD/on-taskgraph/pull/220 https://github.com/RackHD/on-tasks/pull/418
@RackHD/corecommitters @pengz1
=> Refine workflow progress

lib/api/redfish-1.0/update-service.js, spec/lib/api/redfish-1.0/update-service-spec.js, static/redfish.yaml
Perform firmware update on Dell server using Racadm through Redfish API.
=> Redfish UpdateService implementation for Dell

extra/make-clean.sh, extra/make-deb.sh, static/upnp/upnp-device-description.xml.in
Remove installation of on-http-api1.1 
Story: [RAC4654](https://rackhd.atlassian.net/browse/RAC-4654)
=> Remove on-http-api1.1

lib/services/sku-pack-service.js, spec/lib/api/2.0/skus-spec.js, spec/lib/services/sku-pack-service-spec.js, static/monorail-2.0.yaml
=> Add x-view property to /skus/{:id}/nodes route

lib/api/2.0/notification.js, lib/services/notification-api-service.js, spec/lib/api/2.0/notification-spec.js, spec/lib/services/notification-api-service-spec.js, static/monorail-2.0.yaml
@RackHD/corecommitters @RackHD/veyron @yyscamper
=> Add a post route to receive redfish alerts

Dockerfile
@RackHD/corecommitters @tannoa2
=> bug fix for https://rackhd.atlassian.net/browse/RAC-4853\

spec/lib/api/2.0/tasks-spec.js
=> Remove duplicate unit test

static/schemas/2.0/poller.2.0.json
fixing issue where a poller could not be posted to a node.
@RackHD/veyron
=> allowing poller to be posted to a node

data/views/node.2.0.json, lib/services/nodes-api-service.js, spec/lib/api/2.0/nodes-spec.js, spec/lib/api/2.0/skus-spec.js, spec/lib/api/redfish-1.0/system-spec.js, spec/lib/services/nodes-api-service-spec.js, static/monorail-2.0.yaml, static/schemas/2.0/node.2.0.json
- Add IBM settings to node schema
- Change autoDiscover property from string to boolean
=> Fix for switch auto-discovery

lib/api/2.0/nodes.js, lib/services/nodes-api-service.js
Fix issue with `/api/nodes/:id/workflows?actve=true/false`
=> Fix active query for nodes route

data/views/redfish-1.0/redfish.2016.3.computersystem.1.3.0.json, data/views/redfish-1.0/redfish.2016.3.drive.1.1.1.json, data/views/redfish-1.0/redfish.2016.3.storage.1.1.1.json, data/views/redfish-1.0/redfish.2016.3.storagecollection.json, data/views/redfish-1.0/redfish.2016.3.volume.1.0.2.json, data/views/redfish-1.0/redfish.2016.3.volumecollection.json, lib/api/redfish-1.0/systems.js, static/redfish.yaml
on-http code additions. Includes redfish handlers and computer system,
drive, storage, storage collection, volume, and volume collection
views.
=> on-http code

data/templates/secure_erase.py
Move RAID related code to be only executed when disk is with RAID.
This change can make erase cases like all disks are JBOD , or SATADOM/NVMe can be executed.
=>  Decouple-secure-erase-from-RAID-operation

static/monorail-2.0.yaml
creating new `get node` reference for client libraries to get identifier of a node
@RackHD/veyron
=> updating GET node/{id} client lib

data/views/redfish-1.0/redfish.1.0.0.chassis.1.0.0.json, lib/api/redfish-1.0/chassis.js
Remove catalog dependencies from reffish /chassis routes
@RackHD/veyron @RackHD/corecommitters 
Signed-off-by: Geoff Reid <g.reid@>
Signed-off-by: Kranti Uppala <k.uppala@>
=> refactor redfish chassis

data/templates/get_driveid.js, spec/data/templates/get_driveid-spec.js
Issue is encountered to intall ESXi on a Dell R730. It is found ESXi may parse SATA drive WWID differently. So I changed parsing source for SATA drives ESXi WWID:
1. Original source: Ubuntu 'ls -l /dev/disk/by-id' command output string
2. New source: raw hex data got from 'hdparm --Istdout /dev/sdx' command
Also to aligned with what we found, an ASCII code 0x00 will be decoded as '00' instead of an empty string.
Related RAC:
https://rackhd.atlassian.net/browse/RAC-5081
=> Change parsing source for SATA drives ESXi WWID

lib/services/http-service.js, spec/helper.js, static/monorail-2.0-sb.yaml
Signed-off-by: Dale Bremner <dale.bremner@dell.com>
=> Separating North and South bound

lib/api/redfish-1.0/chassis.js, spec/lib/api/redfish-1.0/chassis-spec.js
Signed-off-by: Geoff Reid <geoffrey.reid@dell.com>
Jenkins: depends on https://github.com/RackHD/on-tasks/pull/457, https://github.com/RackHD/ucs-service/pull/22
@RackHD/veyron @RackHD/corecommitters
=> Changes to fix ucs redfish chassis/{id}

lib/services/http-service.js, spec/helper.js, spec/lib/api/2.0/notification-spec.js, spec/lib/api/2.0/templates-spec.js, static/monorail-2.0-sb.yaml
Signed-off-by: Dale Bremner <dale.bremner@dell.com>
=> Split northbound and southbound endpoints

lib/services/http-service.js, spec/helper.js, spec/lib/api/2.0/notification-spec.js, spec/lib/api/2.0/templates-spec.js, static/monorail-2.0-sb.yaml
Signed-off-by: Dale Bremner <dale.bremner@dell.com>
=> Split northbound and southbound endpoints.

data/views/redfish-1.0/redfish.1.0.0.softwareinventory.json, data/views/redfish-1.0/redfish.1.0.0.softwareinventorycollection.json, lib/api/redfish-1.0/update-service.js, spec/lib/api/redfish-1.0/update-service-spec.js, static/redfish.yaml
Signed-off-by: Kranti Uppala <kranti.uppala@emc.com>
=> Implement /Updateservice/Firmwareinventory redfish api

lib/api/redfish-1.0/systems.js
* Month is zero indexed by moment so we had to decrement it
=> RAC-4701 - SEL event date translation error from poller data to redfish

lib/api/redfish-1.0/update-service.js, spec/lib/api/redfish-1.0/update-service-spec.js
Signed-off-by: Dale Bremner <dale.bremner@dell.com>
Signed-off-by: Kranti Uppala <kranti.uppala@emc.com>
=> Non-dell support for redfish updateService/FirmwareInventory APIs

data/views/redfish-1.0/redfish.1.0.0.serviceroot.1.0.0.json, data/views/redfish-1.0/redfish.1.0.0.updateservice.1.0.0.json, lib/api/redfish-1.0/update-service.js, spec/lib/api/redfish-1.0/update-service-spec.js, static/redfish.yaml
UpdateService add :
Status
Service enabled
API links to Firmware Inventory and SoftwareInventory
JSON view
edit Service Root view to:
Add API link to updateService
=> Add properties and other context to redfish UpdateService

lib/services/obm-api-service.js, lib/services/wsman-service.js, spec/lib/services/obm-api-service-spec.js, static/schemas/obms/wsman-obm-service.json
Also: Fixed broken config.obm.userName references.
=> RAC-5617 : Normalize naming of dell-wsman-obm-service

lib/api/redfish-1.0/redfish-root.js, lib/services/http-service.js, spec/helper.js, spec/lib/api/redfish-1.0/redfish-root-spec.js, static/redfish-root.yaml
Adding support for the API /redfish endpoint.
This is to meet the Redfish Specification.
=> RAC-5616 - Add redfish root endpoint for Redfish Spec compliance

lib/api/redfish-1.0/odata.js, spec/lib/api/redfish-1.0/odata-spec.js, static/redfish.yaml
* Add odata redfish api endpoint
* Add odata.js
* Add odata spec test
=> RAC-5637 Add odata endpoint for redfish compliance tests

static/redfishMetadata.xml
=> RAC-5669 redfish/v1/$metadata - on-http/static/redfishMetadata.xml has mismatched tags

data/views/redfish-1.0/redfish.1.0.0.manager.1.0.0.json, data/views/redfish-1.0/redfish.1.0.0.serialinterface.1.0.0.json, data/views/redfish-1.0/redfish.1.0.0.serialinterfacecollection.json, lib/api/redfish-1.0/managers.js, spec/lib/api/redfish-1.0/managers-spec.js, static/redfish.yaml
Add implementation to SerialInterfaceCollection and SerialInterface routes. 
=> Redfish SerialInterface GET APIs

data/templates/esx-ks
Document update is here: https://github.com/RackHD/docs/pull/396
=> Added arguments to respect kargs & vswitch failover policy

spec/lib/api/2.0/nodes-spec.js, static/monorail-2.0.yaml
The current swagger file and tests do not match.
https://github.com/RackHD/on-http/blob/master/static/schemas/obms/ipmi-obm-service.json
=> Update Swagger OBM Settings to match json schema

lib/services/nodes-api-service.js, spec/lib/services/nodes-api-service-spec.js
Promise.reject from within map composition is not proper.
=> RAC-5761 - Fix nodes-api-service check for node self ref.

data/views/redfish-1.0/redfish.1.0.0.redfishstorage.1.0.0.json, lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
Modify existing code to present Storage API using Redfish catalog as well.
=> implement Storage api using Redfish catalog info

data/views/redfish-1.0/redfish.1.0.0.taskcollection.json
* Remove embedded tasks object
=> RAC-5752 - Support for TaskCollection compliance changes

lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
* Create valid odtata linkes for non-dell devices
* Added veiw for ethernetintercae/index for non-dell devices
* Correct spec tests to allow ethernetinterface for non-dell devices
=> RAC-5682 - Redfish Compliance, correct systems/ethernetinterface odata links for non-dell

.travis.yml
Due to https://github.com/RackHD/on-core/pull/288 have fix the mongodb compatibility problem. remove previous fixed OS versiono
=> Remove fixed precise/12.04 unittest environment

data/views/redfish-1.0/redfish.1.0.0.ethernetinterface.1.0.0.json, lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
* Both DELL and non-DELL catalogs supported
=> rac-5799 - Populate IPv4 and IPv6 IPs if available

lib/api/redfish-1.0/systems.js, static/redfish.yaml
Need for consistency across the api calls.
Paired with Derrick on this.
@derrickostertag @jimturnquist
=> RAC-5683 - Update 'sel' to 'SEL' in redfish api commands.

.travis.yml, extra/make-deb.sh
See [on-dhcp-proxy 73](https://github.com/RackHD/on-dhcp-proxy/pull/73)
=> [RAC-5774]add deb build in on-http's TravisCI .

lib/services/http-service.js
Signed-off-by: Geoff Reid <geoff.reid@dell.com>
=> Make on-taskgraph a stand alone service

data/views/redfish-1.0/redfish.2016.3.drive.1.1.1.json, data/views/redfish-1.0/redfish.2016.3.storage.1.1.1.json, lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
rac-5926 - increase unit testing = 90%+
* All calls now have test for both DELL and non-Dell devices as appropriate
* Corrected error in logic as found
* Added or increases mock catalogs
=> rac-5884 - Continuation of convertion systems.js to use wsman.isDell system(identifier)

lib/api/redfish-1.0/metadata.js, lib/services/swagger-api-service.js, spec/lib/api/redfish-1.0/metadata-spec.js
* Change metadata.js to return application/xml content-type
* Change metadata-spec.js to expect application/xml content-type
Paired with @pathakvaidehi2391
=> rac-5975 - serviceroot not returning xml/json data properly

Dockerfile, HWIMO-BUILD, alpha/build_deb.sh, alpha/build_deb.yml, alpha/build_docker.sh, alpha/build_docker.yml, alpha/pipeline.yml, alpha/post_build_deb.yml, alpha/post_unittest.yml, alpha/set_dependencies.sh, alpha/unittest.sh, alpha/unittest.yml
=> adding concourse CI testing

HWIMO-TEST
Fix: recover the environment after test.
@anhou @iceiilin @panpan0000
=> RAC-5843 : restore environment even if test failed

lib/api/redfish-1.0/schemas.js, spec/lib/api/redfish-1.0/schemas-spec.js
Added xml content type to redfish header.
Paired with Derrick
@derrickostertag @jimturnquist
=> RAC-6014 fix redfish xml header

data/views/redfish-1.0/redfish.1.0.0.taskservice.1.0.0.json
Removed elements in URI that were failing validator.
Paired with Derrick
@derrickostertag @jimturnquist
=> RAC-5913 fix bad URI in taskservice

data/views/redfish-1.0/redfish.1.0.0.logentry.1.0.0.json, data/views/redfish-1.0/redfish.1.0.0.logentrycollection.json
Fixed originOfCondition Redfish errors revealed by the validation test.
Requires FIT test correction.
Paired with Derrick
@derrickostertag @jimturnquist
=> RAC-6023 fix orginOfCondition Redfish errors

lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js, static/redfish.yaml
* Added ResetBios Redfish Api Endpoint
* Added spec tests for ResetBios
=> RAC-4910 Added systems/{identifier}/Bios.ResetBios

data/views/redfish-1.0/redfish.1.0.0.serviceroot.1.0.0.json
=> RAC-6039: Redfish Compliance - /redfish/v1/UpdateService failure

data/views/redfish-1.0/redfish.1.0.0.role.1.0.0.json
Paired with @gpaulos 
@jimturnquist
=> RAC-6033 - Fix /redfish/v1/AccountService/Roles failures

lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
**Background**
----
UCS redfish is broke GET /Systems/{identifier}/SimpleStorage
----
Details
----
1. Implemented /Systems/{identifier}/SimpleStorage API to get Dell/Cisco/Other simple storage controllers.
@iceiilin  @anhou @pengz1 @yaolingling
=> RAC 5099 Implement UCS redfish Api GET /Systems/{identifier}/SimpleStorage

data/views/redfish-1.0/redfish.1.0.0.chassis.1.0.0.json, data/views/redfish-1.0/redfish.1.0.0.computersystem.1.0.0.json, data/views/redfish-1.0/redfish.1.0.0.computersystem.1.1.0.json, lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
Fix SecureBoot for non-Dells
Work in progess - DO NOT MERGE
Paired with @gpaulos & @jimturnquist
=> RAC-6045 Fix Redfish Compliance - /redfish/v1/Systems failures

data/views/redfish-1.0/redfish.1.0.0.storage.1.0.0.json, lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
* Modified  getDevice() to correctly display SATADOM devices
* Added spec tests
Paired with @gpaulos
=> rac-6062 - remove volumes from non-dell (wsman) catalog devices

data/views/redfish-1.0/redfish.1.0.0.updateservice.1.0.0.json, static/redfish.yaml
@pathakvaidehi2391 @jimturnquist
=> RAC-6102 Redfish actions properties/links in updateservice

lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
* Added Empty conroller dictionary to spec test SMART catalog mock
=> rac-6103 - Correction for empty controller dictionary

lib/api/redfish-1.0/chassis.js, spec/lib/api/redfish-1.0/chassis-spec.js
**Background**
----
We need to extend Chassis/{identifier}/Thermal API for UCS. 
[https://rackhd.atlassian.net/browse/RAC-5082](https://rackhd.atlassian.net/browse/RAC-5082)
**AC**:
- API implemented
- Unit test added
**Detail**
----
- Extend Chassis/{identifier}/Thermal API for UCS system
- Extend unit test for Chassis/{identifier}/Thermal API
@iceiilin @anhou @pengz1 @bbcyyb
=> RAC-5082 Add extension for ucs chassis thermal api and its unit tests

lib/api/redfish-1.0/chassis.js, spec/lib/api/redfish-1.0/chassis-spec.js
**Background**
----
We need to extend Chassis/{identifier}/Power API for UCS. 
[https://rackhd.atlassian.net/browse/RAC-5083](https://rackhd.atlassian.net/browse/RAC-5083)
**AC**:
- API implemented
- Unit test added
**Detail**
----
- Extend Chassis/{identifier}/Power API for UCS system
- Extend unit test for Chassis/{identifier}/Power API
@iceiilin @anhou @pengz1 @bbcyyb
=> RAC-5083 Add extension for ucs chassis Power api and its unit tests

lib/api/redfish-1.0/update-service.js, spec/lib/api/redfish-1.0/update-service-spec.js, static/redfish.yaml, static/redfishMetadata.xml
We did some code refactoring and added the SoftwareInventory back to the Redfish UpdateService
@jimturnquist  @pathakvaidehi2391 @patelb10
=> RAC-6111 Add back SoftwareInventory to Redfish UpdateService

lib/services/wsman-service.js
**Background**
As the RACADM replacement work squad, we need to work on common wsman-tools functionality, so that everyone can focus on their own tasks.
**Details**
refactor WsmanTool
**Reviewers**
@RackHD/corecommitters @nortonluo @yaolingling
=> [RAC-6176] refactor WsmanTool

lib/api/redfish-1.0/systems.js
=> create default datafactory behavior for systems.js

static/monorail-2.0.yaml, static/redfish.yaml
=> update monorail-2.0.yaml and redfish.yaml to test pypi builds

lib/api/redfish-1.0/event-service.js, package.json, spec/lib/api/redfish-1.0/event-service-spec.js
Create the PR for krein:
https://github.com/RackHD/on-http/pull/808
=> Fix-on-http-unittest-timeout-issue

data/views/redfish-1.0/redfish.1.0.0.rackhd.reset.actions.json, lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js, static/DSP8010_2016.3/json-schema-oem/RackHD.ResetAction.json, static/redfish.yaml
Fix for [RAC-6473](https://rackhd.atlassian.net/browse/RAC-6473)
depends on: https://github.com/RackHD/RackHD/pull/904
=> changed reset_type to ResetType to match Redfish standard

install-swagger-ui.sh, install-web-ui.sh
**Background**
----
Because of occasionally network fail, curl may fail in install-swagger-ui.sh and install-web-ui.sh
[https://rackhd.atlassian.net/browse/RAC-4894](https://rackhd.atlassian.net/browse/RAC-4894)
**Detail**
----
Add curl retry.
@iceiilin @anhou @pengz1 @bbcyyb @PengTian0
=> Add retry in swagger and web ui script

data/views/redfish-1.0/redfish.1.0.0.DCIMCoolingDomainCollection.json, data/views/redfish-1.0/redfish.1.0.0.DCIMPowerDomainCollection.json, static/DSP8010_2016.3/metadata/ServiceRoot_v1.xml, static/redfish.yaml, static/redfishMetadata.xml
The redfish service validator was failing for a variety of reasons.
This fixes all issues related to DCIMCooling and Power changes that
have been made.
Update post schema for ManagerAccount to not use allOf schema construct.
=> RAC-6534 Fix variety of RedfishServiceValidator issues

spec/lib/api/2.0/callback-spec.js, static/monorail-2.0.yaml
=> add ucsCallback to north bound

package.json
depends on: RackHD/on-taskgraph#351
@keedya @dalebremner
=> lock grpc version to ~1.7.0

lib/api/redfish-1.0/systems.js, spec/lib/api/redfish-1.0/system-spec.js
**Background**
To port add & delete volume redfish api, the graph need to be replaced with new graphs. Details in https://rackhd.atlassian.net/browse/RAC-6553.
**Reviewers**
@nortonluo @lanchongyizu @AlaricChan
=> RAC-6553 Port add & delete volume redfish api

Dockerfile
=> fix Dockerfile to use correct apidoc version for taskdoc

lib/services/upnp-service.js
Signed-off-by: Azzam Tannous <Azzam.Tannous@dell.com>
=> fix upnp service to return new southbound route

lib/api/redfish-1.0/systems.js
**Background**
This story is to implement adding hot spare via WSMAN, replace the RACADM dependencies in Redfish API with WSMAN implementation.
**Details**
Replace reference of RACADM graph with new created WSMAN graph
**Dependency**
depends on: https://github.com/RackHD/on-taskgraph/pull/355 https://github.com/RackHD/on-tasks/pull/576
**Reviewer**
@yaolingling @pengz1 @nortonluo
=> [RAC-6492] Port racadm based add-hotspare redfish API with wsman implementation
